'use strict';
const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto'),cp=require('node:child_process');
const sourceVersion='sunward-source-v4.1';
function write(n,data){if(path.isAbsolute(n)||n.split(/[\\/]/).includes('..'))throw Error('Unsafe path');fs.mkdirSync(path.dirname(n),{recursive:true});fs.writeFileSync(n,data);}
const env={...process.env,SUNWARD_LIVE:'false',SITE_URL:'',LEAD_WEBHOOK_URL:'',LEAD_ENDPOINT_APPROVED:'false'};
for(const script of ['scripts/cache-map.mjs','scripts/build.mjs','scripts/upgrade.mjs','scripts/trust.mjs'])cp.execFileSync(process.execPath,[script],{stdio:'inherit',env});
fs.rmSync('dist/studio',{recursive:true,force:true});fs.rmSync('dist/studio-src',{recursive:true,force:true});fs.cpSync('studio-app','dist/studio',{recursive:true});fs.cpSync('studio-src','dist/studio-src',{recursive:true});
fs.rmSync('dist/growth',{recursive:true,force:true});fs.cpSync('growth','dist/growth',{recursive:true});write('dist/start/index.html',fs.readFileSync('growth/start.html','utf8'));
const home='dist/index.html';if(fs.existsSync(home)){let html=fs.readFileSync(home,'utf8');const studioCta=`<a class="sunward-studio-launch" href="/studio/" aria-label="Design and price your solar system"><span>NEW · SUNWARD STUDIO</span><strong>Design my system</strong><em>→</em></a><style>.sunward-studio-launch{position:fixed;right:20px;bottom:20px;z-index:88;display:grid;grid-template-columns:1fr auto;gap:2px 18px;align-items:center;min-width:245px;padding:14px 16px;border-radius:16px;background:#10271f;color:#fff;text-decoration:none;box-shadow:0 15px 42px #10271f44}.sunward-studio-launch span{grid-column:1;font:700 9px/1.2 system-ui;letter-spacing:.12em;color:#d9ff64}.sunward-studio-launch strong{grid-column:1;font:800 15px/1.2 system-ui}.sunward-studio-launch em{grid-column:2;grid-row:1/3;font:normal 24px system-ui;color:#d9ff64}@media(max-width:600px){.sunward-studio-launch{display:none}}</style>`;if(!html.includes('sunward-studio-launch'))html=html.replace('</body>',studioCta+'</body>');fs.writeFileSync(home,html);}
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);}
const htmlFiles=walk('dist').filter(f=>f.endsWith('.html'));
for(const file of htmlFiles){let html=fs.readFileSync(file,'utf8');if(!file.includes('dist/studio/')&&!html.includes('/growth/growth.css'))html=html.replace('</head>','<link rel="stylesheet" href="/growth/growth.css"></head>');if(!html.includes('/growth/growth.js'))html=html.replace('</body>','<script src="/growth/growth.js" defer></script></body>');if(!html.includes('/growth/acquisition.js'))html=html.replace('</body>','<script src="/growth/acquisition.js" defer></script></body>');html=html.replace(/<img(?![^>]*loading=)([^>]*?)>/g,(m,a)=>/hero|logo|fetchpriority/i.test(a)?m:`<img loading="lazy" decoding="async"${a}>`);fs.writeFileSync(file,html);}

const corePaths=['index.html','solar-pv/index.html','battery-storage/index.html','solar-and-battery-storage/index.html','tariffs/index.html','tariffs/import/index.html','tariffs/export/index.html','products/index.html','battery-storage/duracell/index.html','solar-pv/aiko/index.html','locations/index.html','studio/index.html'];
const seoRows=corePaths.filter(p=>fs.existsSync(path.join('dist',p))).map(p=>{const html=fs.readFileSync(path.join('dist',p),'utf8');const title=(html.match(/<title>([^<]*)<\/title>/i)||[])[1]||'';const desc=(html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)||html.match(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i)||[])[1]||'';const h1=(html.match(/<h1\b/gi)||[]).length;const multiView=p==='studio/index.html';const h1Pass=multiView?h1>=1:h1===1;return {path:p==='index.html'?'/':'/'+p.replace(/index\.html$/,''),title:title.trim(),descriptionLength:desc.trim().length,h1Count:h1,h1Mode:multiView?'multi-view-app':'single-page',pass:Boolean(title.trim()&&desc.trim()&&h1Pass)};});
const failedCore=seoRows.filter(r=>!r.pass);write('dist/seo-audit.json',JSON.stringify({preview:true,checkedAt:new Date().toISOString(),core:seoRows,failedCore,count:seoRows.length},null,2));if(failedCore.length)throw Error('Core SEO guardrail failed: '+failedCore.map(x=>x.path).join(', '));

const studioFiles=['dist/studio/app.js','dist/studio/styles.css','dist/studio-src/catalogue.mjs','dist/studio-src/engine.mjs','dist/studio-src/scene.mjs','dist/trust/data.mjs'];const studioGzip=studioFiles.reduce((a,f)=>a+zlib.gzipSync(fs.readFileSync(f)).length,0);if(studioGzip>45000)throw Error('Studio transfer budget exceeded');const imageBytes=walk('dist/studio/assets').reduce((a,f)=>a+fs.statSync(f).size,0);if(imageBytes>200000)throw Error('Studio image budget exceeded');write('dist/studio-budget.json',JSON.stringify({scriptAndStyleGzipBytes:studioGzip,budgetGzipBytes:45000,productImageBytes:imageBytes,imageBudgetBytes:200000}));
const trustFiles=['dist/trust/trust.js','dist/trust/trust.css','dist/trust/data.mjs'];const trustGzip=trustFiles.reduce((a,f)=>a+zlib.gzipSync(fs.readFileSync(f)).length,0);if(trustGzip>20000)throw Error('Trust layer gzip budget exceeded');write('dist/trust-budget.json',JSON.stringify({gzipBytes:trustGzip,budgetBytes:20000,videoRequestsBeforeActivation:0}));
const perfFiles=['dist/growth/growth.css','dist/growth/growth.js','dist/growth/acquisition.js'];const perf=perfFiles.map(file=>({file:file.replace('dist/','/'),bytes:fs.statSync(file).size,gzipBytes:zlib.gzipSync(fs.readFileSync(file)).length}));const perfTotal=perf.reduce((a,x)=>a+x.gzipBytes,0);write('dist/performance-budget.json',JSON.stringify({assets:perf,totalGzipBytes:perfTotal,budgetGzipBytes:30000,pass:perfTotal<=30000,targets:{LCP_ms:2500,INP_ms:200,CLS:0.1}},null,2));if(perfTotal>30000)throw Error(`Growth layer performance budget exceeded: ${perfTotal} gzip bytes`);

write('dist/acquisition.json',JSON.stringify({version:'1.3',primaryConversion:'/studio/',campaignEntry:'/start/',secondaryConversion:'/tariffs/',events:['page_view','engaged_cta_shown','internal_click','studio_step_view','studio_step_change','property_lookup_focus','property_lookup_submit','manual_property_selected','roof_autofill','system_change','quote_primary_action','acquisition_intent','campaign_goal_applied','web_vitals'],attribution:['utm_source','utm_medium','utm_campaign','utm_content','utm_term','gclid','fbclid']}));
write('dist/robots.txt','User-agent: *\nDisallow: /\n');
write('dist/deployment-info.json',JSON.stringify({version:'4.1-trust-preview',preview:true,sourceVersion,commit:process.env.VERCEL_GIT_COMMIT_SHA||null,studio:true,growth:true,campaignStart:true,seoGuardrails:true,performanceBudget:true,htmlPages:htmlFiles.length}));
console.log(`Verified Sunward v2 + Studio + growth layer across ${htmlFiles.length} HTML pages as a non-sending, non-indexed preview. Growth gzip ${perfTotal} bytes.`);
