// Public supplier pages checked 7 September 2026. Recheck before a commercial release.
export const CHECKED = '7 September 2026';
export const CHECKED_ISO = '2026-09-07';
export const PROFILES = {
  solar: {name:'Solar panels', goal:'solar', title:'Keep import costs low. Give surplus solar a fair price.', text:'With no battery, most spare generation leaves at lunchtime. A flat export rate is easier to use than an evening premium. Compare the remaining import bill as well as export income.', shortlist:['outgoing','ovo-export','bg-export','eon-export'], caution:'A high export price cannot compensate for every expensive import tariff. Compare both sides using your actual annual kWh.'},
  both: {name:'Solar + battery', goal:'both', title:'Match the battery to your evenings, then match the tariff.', text:'Storage can move daytime solar into the evening. A time-of-use tariff adds another choice: charge cheaply or export when prices are higher. The useful capacity and your routine matter more than the headline rate.', shortlist:['flux','prime','charge-power','outgoing'], caution:'Exporting a full battery at peak time can leave you buying energy later. Keep a reserve for your own demand and account for charging losses.'},
  battery: {name:'Battery, no solar', goal:'battery', title:'Start with the gap between cheap and expensive hours.', text:'A battery needs to replace enough costly imports to earn its keep. Choose a tariff you qualify for without an EV, then check charging power, usable capacity and daytime demand.', shortlist:['charge-power'], caution:'A home battery does not make you eligible for an EV tariff. At 90% round-trip efficiency, delivering 1 kWh needs about 1.11 kWh of charging.'},
  ev: {name:'EV + home energy', goal:'both', title:'Cheap car charging is only part of the bill.', text:'If you charge at home regularly, a long overnight window may also suit your battery. Smart offers need compatible equipment. An EV-only credit leaves the rest of your household electricity at its usual price.', shortlist:['eon-smart','intelligent-go','eon-drive','bg-ev','ovo-charge'], caution:'E.ON Next Export Exclusive excludes time-of-use import tariffs such as Next Drive. Check the export option alongside the EV quote.'},
  heat: {name:'Heat pump', goal:'both', title:'Look beyond one overnight window.', text:'Heating demand often arrives in the morning and evening. Several cheaper periods can be useful when your home retains heat well. Model winter demand and maintain comfortable temperatures.', shortlist:['cosy','charge-power','outgoing'], caution:'Cosy has a more expensive 16:00–19:00 period. Its value depends on how much heating and other use you can move without sacrificing comfort.'}
};
export const TARIFFS = [
 {id:'intelligent-go',supplier:'Octopus Energy',name:'Intelligent Octopus Go',type:'import',headline:'8p',unit:'/ kWh off-peak',window:'23:30–05:30',hours:[[23.5,24],[0,5.5]],offpeak:8,scope:'Whole home overnight + eligible smart EV charging',fit:'Regular home EV charging with a compatible car or charger.',why:'Six predictable overnight hours can also support a home battery and flexible household use.',checks:'Working smart meter, half-hourly readings and supported EV or charger. Day rate and standing charge require a postcode quote. Bump charging costs more.',source:'https://octopus.energy/smart/intelligent-octopus-go/'},
 {id:'ovo-charge',supplier:'OVO',name:'Charge Anytime · pay as you go',type:'import',headline:'14p',unit:'/ kWh smart EV charging',window:'Smart scheduled EV charging',hours:[],offpeak:null,scope:'EV charging credit only',fit:'EV drivers who want to keep their existing OVO home tariff.',why:'Credits reduce the price of eligible smart car charging while your home energy rate stays unchanged.',checks:'Compatible EV or charger, smart meter and OVO account. Boost charging uses the normal home rate. Monthly plans also exist; their allowances and fees need a separate comparison.',source:'https://www.ovoenergy.com/electric-cars/charge-anytime'},
 {id:'bg-ev',supplier:'British Gas',name:'EV Power',type:'import',headline:'9p',unit:'/ kWh off-peak',window:'00:00–05:00',hours:[[0,5]],offpeak:9,scope:'Whole home during the off-peak window',fit:'EV owners who prefer to set their own charging schedule.',why:'A fixed five-hour window works with any make of EV and home charger.',checks:'EV charged at home, working smart electricity meter and Direct Debit. Daytime rates are higher; get your postcode quote. Separate Hive credits have additional conditions.',source:'https://www.britishgas.co.uk/energy/ev-tariff.html'},
 {id:'eon-smart',supplier:'E.ON Next',name:'Next Drive Smart',type:'import',headline:'6.9p',unit:'/ kWh off-peak',window:'00:00–07:00',hours:[[0,7]],offpeak:6.9,scope:'Whole home overnight + eligible smart EV charging',fit:'Compatible EV households with substantial flexible demand.',why:'Seven overnight hours give a longer window for car, battery and household demand.',checks:'Eligible EV and charger, smart meter and half-hourly consent. Boost charging during peak hours uses the peak rate. Get regional day and standing rates. Excludes Next Export Exclusive.',source:'https://www.eonnext.com/tariffs/next-drive'},
 {id:'eon-drive',supplier:'E.ON Next',name:'Next Drive',type:'import',headline:'8.5p',unit:'/ kWh off-peak',window:'00:00–07:00',hours:[[0,7]],offpeak:8.5,scope:'Whole home during the off-peak window',fit:'EV households wanting scheduled overnight charging.',why:'Seven hours of cheaper home electricity without relying on the Smart offer’s device control.',checks:'EV tariff eligibility and half-hourly smart meter data required. One-year fixed rates, no exit fees. Day and standing rates need a quote. Excludes Next Export Exclusive.',source:'https://www.eonnext.com/tariffs/next-drive'},
 {id:'charge-power',supplier:'British Gas',name:'Charge Power',type:'import',headline:'50%',unit:'off the unit rate overnight',window:'00:00–05:00',hours:[[0,5]],offpeak:null,scope:'Whole home during the off-peak window',fit:'A home battery, with or without solar or an EV.',why:'Open to home battery owners, so you do not need to buy an EV to explore overnight charging.',checks:'Battery installed, British Gas supply, half-hourly smart meter data and fixed Direct Debit. Standing charge is not discounted. Obtain the underlying unit rate; 50% is not a p/kWh price.',source:'https://www.britishgas.co.uk/energy/home-battery-tariff.html'},
 {id:'flux',supplier:'Octopus Energy',name:'Octopus Flux',type:'combined',headline:'3',unit:'daily import & export periods',window:'02:00–05:00 cheap · 16:00–19:00 peak',hours:[[2,5]],offpeak:null,scope:'Combined import and export tariff',fit:'Solar + battery owners able to manage charging schedules.',why:'Cheaper overnight imports and peak export payments can reward shifting energy into the evening.',checks:'Solar, battery, half-hourly smart meter and both import and export with Octopus. Rates vary by postcode. Peak imports also cost more. Intelligent Flux has separate battery compatibility rules.',source:'https://octopus.energy/smart/flux/'},
 {id:'cosy',supplier:'Octopus Energy',name:'Cosy Octopus',type:'import',headline:'8',unit:'cheaper hours across the day',window:'04:00–07:00 · 13:00–16:00 · 22:00–00:00',hours:[[4,7],[13,16],[22,24]],offpeak:null,scope:'Whole-home rates for eligible electric heating',fit:'Heat pumps, electric boilers or electric radiators.',why:'Three cheaper periods can better follow heating demand than a single overnight window.',checks:'Eligible electric heating and half-hourly smart meter data. Cheap hours are 51% below the regional day rate; 16:00–19:00 is 50% above it. Quote all three rates.',source:'https://octopus.energy/smart/cosy-octopus/'},
 {id:'outgoing',supplier:'Octopus Energy',name:'Outgoing Octopus',type:'export',headline:'12p',unit:'/ kWh exported',window:'Same rate, all day',hours:[],export:12,scope:'Flat variable export rate',fit:'Solar owners who prefer a simple export payment.',why:'Lunchtime surplus earns the same unit price as evening exports.',checks:'Eligible installation, export MPAN and half-hourly smart meter data. Only certain import tariffs can be paired. Rates can change; confirm the combination with Octopus.',source:'https://octopus.energy/smart/outgoing/'},
 {id:'prime',supplier:'Octopus Energy',name:'Prime Outgoing Octopus',type:'export',headline:'16p',unit:'/ kWh, 16:00–19:00',window:'9p/kWh at other times',hours:[[16,19]],export:null,scope:'Time-of-use export',fit:'Solar + battery owners able to shift surplus into the evening.',why:'The evening premium can help if you have energy left after your own needs.',checks:'The rate is lower than flat Outgoing outside the peak window. At equal export volume, more than 43% must fall in the peak window to beat 12p flat, before storage losses. Confirm import compatibility.',source:'https://octopus.energy/smart/outgoing/'},
 {id:'ovo-export',supplier:'OVO',name:'SEG Beyond Exclusive',type:'export',headline:'12p',unit:'/ kWh exported',window:'Flat export payment',hours:[],export:12,scope:'For qualifying OVO electricity customers',fit:'Existing solar owners considering OVO for home electricity.',why:'The higher customer export rate may suit you if the accompanying import quote also works.',checks:'Renewable capacity below 30 kW and other SEG requirements apply. Standard SEG is 4p with any import supplier. Install Exclusive pays 15p for OVO solar or 20p for OVO solar + battery; those installation-only offers are not assumed here.',source:'https://www.ovoenergy.com/smart-export-guarantee'},
 {id:'bg-export',supplier:'British Gas',name:'Export Premium',type:'export',headline:'12p',unit:'/ kWh exported',window:'Flat variable export rate',hours:[],export:12,scope:'British Gas electricity customers · up to 15 kW',fit:'Qualifying solar owners already with British Gas or comparing a switch.',why:'A straightforward export payment can accompany a suitable home import tariff.',checks:'Rate updated by supplier on 27 August 2026. Certified generation, smart export metering and DNO paperwork required. Export Extra is 8p for larger systems. These customer rates do not apply to every applicant.',source:'https://www.britishgas.co.uk/energy/smart-export-guarantee-tariff.html'},
 {id:'eon-export',supplier:'E.ON Next',name:'Next Export Exclusive v3',type:'export',headline:'13p',unit:'/ kWh exported',window:'12-month fixed export rate',hours:[],export:13,scope:'Qualifying E.ON Next import customers',fit:'Solar owners on an eligible standard import tariff.',why:'A flat export rate rewards daytime surplus without needing battery dispatch.',checks:'Residential renewable system up to 15 kW. Excludes time-of-use import tariffs, including Next Drive. Premium v3 is 17.5p for qualifying E.ON installations from 10 November 2025, for one term. Next Flex Export is 6p variable.',source:'https://www.eonnext.com/electricity-and-gas/smart-export-guarantee'}
];
export function getProfile(key){return PROFILES[key]||PROFILES.both;}
export function shortlist(key){return getProfile(key).shortlist.map(id=>TARIFFS.find(t=>t.id===id));}
export function compareBill({annual,share,day,night,standing,baseRate,baseStanding,exports=0,exportRate=0,baseExportRate=0}){
 const values=[annual,share,day,night,standing,baseRate,baseStanding,exports,exportRate,baseExportRate].map(Number);
 if(values.some(v=>!Number.isFinite(v))||annual<0||share<0||share>100||[day,night,standing,baseRate,baseStanding,exports,exportRate,baseExportRate].some(v=>v<0))return null;
 const cheap=annual*share/100,regular=annual-cheap;
 const candidate=(regular*day+cheap*night+standing*365-exports*exportRate)/100;
 const baseline=(annual*baseRate+baseStanding*365-exports*baseExportRate)/100;
 const required=day===night?null:((annual*(day-baseRate)+365*(standing-baseStanding)-exports*(exportRate-baseExportRate))/(annual*(day-night)))*100;
 return {candidate,baseline,difference:baseline-candidate,cheap,regular,required:annual>0?required:null};
}
