const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const track=(name,data={})=>window.SunwardGrowth?.event(name,data);
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
function reveal(){if(reduced()||!('IntersectionObserver' in window))return;const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){e.target.classList.add('t-seen');observer.unobserve(e.target);}},{threshold:.12});$$('.t-reveal').forEach(el=>observer.observe(el));}
reveal();

// No external video request is made before a visitor chooses a film.
const dialog=$('.t-video-dialog');let mediaPromise,videoRequest=0,videoTrigger;
if(dialog){
 $$('[data-video]').forEach(button=>button.addEventListener('click',async()=>{
  videoTrigger=button;const request=++videoRequest;const mount=$('[data-video-mount]',dialog);mount.replaceChildren();$('#t-video-title').textContent='Loading product film…';$('[data-video-context]',dialog).textContent='';dialog.showModal();document.body.classList.add('modal-open');
  try{mediaPromise ||= fetch('/trust/media.json',{credentials:'omit'}).then(r=>{if(!r.ok)throw Error('Unavailable');return r.json()});const manifest=await mediaPromise;if(request!==videoRequest||!dialog.open)return;const v=manifest.videos.find(v=>v.id===button.dataset.video);if(!v)throw Error('Unavailable');
   $('#t-video-title').textContent=v.title;$('[data-video-context]',dialog).textContent=v.context+(v.type==='youtube'?' YouTube loads when you play this film.':' Use the player controls to start, pause or expand the film.');const source=$('[data-video-source]',dialog);source.href=v.sourcePage;
   if(v.type==='youtube'){const player=document.createElement('iframe');player.src='https://www.youtube-nocookie.com/embed/'+v.youtubeId;player.title=v.title;player.allow='accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen';player.referrerPolicy='strict-origin-when-cross-origin';player.allowFullscreen=true;mount.append(player);}
   else{const player=document.createElement('video');player.src=v.url;player.poster=v.localPoster;player.controls=true;player.playsInline=true;player.preload='none';player.setAttribute('aria-label',v.title);player.addEventListener('error',()=>{$('[data-video-context]',dialog).textContent='The film could not load here. You can still watch it on the manufacturer’s website below.';},{once:true});mount.append(player);}
   track('manufacturer_video_open',{manufacturer:v.brand,video:v.id});
  }catch{mediaPromise=null;$('#t-video-title').textContent='The film is unavailable';$('[data-video-context]',dialog).textContent='Please use the manufacturer source link on the film card.';$('[data-video-source]',dialog).removeAttribute('href');}
 }));
 $('[data-video-close]',dialog).addEventListener('click',()=>dialog.close());
 dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
 dialog.addEventListener('close',()=>{videoRequest++;const video=$('video',dialog);if(video)video.pause();$('[data-video-mount]',dialog).replaceChildren();document.body.classList.remove('modal-open');videoTrigger?.focus({preventScroll:true});});
}

async function initTariffs(){
 const {PROFILES,TARIFFS,compareBill}=await import('./data.mjs');
 const cards=new Map($$('[data-tariff-card]').map(el=>[el.dataset.tariffCard,el]));const results=$('[data-tariff-results]');let selected='both';
 function selectProfile(key,all=false){if(!PROFILES[key])key='both';selected=key;const p=PROFILES[key];$$('[data-setup]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.setup===key)));$('[data-profile-title]').textContent=p.title;$('[data-profile-text]').textContent=p.text;$('[data-profile-caution]').textContent=p.caution;$('[data-profile-cta]').href='/studio/?goal='+p.goal+(key==='ev'?'&ev=1':key==='heat'?'&heatpump=1':'');
  const order=all?TARIFFS.map(t=>t.id):p.shortlist;results.dataset.odd=String(order.length%2===1);for(const[id,card]of cards){card.hidden=!order.includes(id);}order.forEach(id=>results.append(cards.get(id)));$('[data-results-title]').textContent=all?'All supplier examples':p.name+' · starting shortlist';$('[data-show-all]').textContent=all?'Back to my shortlist':'Show all supplier examples';$('[data-show-all]').dataset.all=String(all);
  const url=new URL(location.href);url.searchParams.set('setup',key);history.replaceState(null,'',url);track('tariff_setup_selected',{setup:key,view:all?'all':'shortlist'});
 }
 if(results){$$('[data-setup]').forEach(b=>b.addEventListener('click',()=>selectProfile(b.dataset.setup)));$('[data-show-all]').addEventListener('click',e=>selectProfile(selected,e.currentTarget.dataset.all!=='true'));const param=new URLSearchParams(location.search).get('setup');selectProfile(PROFILES[param]?param:location.pathname.includes('/export/')?'solar':'both');}
 const form=$('[data-bill-form]');if(!form)return;const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
 function calculate(){const fields=$$('[data-bill]',form),data=Object.fromEntries(fields.map(el=>[el.dataset.bill,Number(el.value)]));$('[data-share-value]').textContent=data.share+'%';const valid=fields.every(el=>el.value!==''&&el.checkValidity()),r=valid?compareBill(data):null;
  if(!r){$('[data-bill-threshold]').textContent='Enter valid positive rates and annual usage to compare these examples.';['baseline','candidate','saving'].forEach(k=>$('[data-bill-'+k+']').textContent='—');return;}
  $('[data-bill-baseline]').textContent=money(r.baseline);$('[data-bill-candidate]').textContent=money(r.candidate);$('[data-bill-saving]').textContent=money(Math.abs(r.difference))+(Math.abs(r.difference)<.5?' difference':r.difference>=0?' less':' more');$('[data-bill-saving-label]').textContent=r.difference>=0?'Lower annual cost on these inputs':'Higher annual cost on these inputs';
  $('[data-bill-threshold]').textContent=r.required===null?'The result depends on your entered rates and standing charges.':data.day<=data.night?'Your off-peak rate is not below the day rate. Check the quote before relying on overnight savings.':r.required>100?'Even moving all import off-peak would not beat your current tariff on these inputs.':r.required<=0?'These example rates cost less even without shifting import off-peak.':'Shift more than '+Math.ceil(r.required)+'% of grid imports off-peak to beat the current cost on these inputs.';
 }
 form.addEventListener('input',calculate);form.addEventListener('submit',e=>e.preventDefault());calculate();
 $$('[data-rate-preset]').forEach(b=>b.addEventListener('click',()=>{const t=TARIFFS.find(t=>t.id===b.dataset.ratePreset);if(!t||typeof t.offpeak!=='number')return;$('[data-bill="night"]').value=t.offpeak;$('[data-bill-preset]').textContent=t.name+': published '+t.offpeak+'p/kWh overnight rate. Day rate, standing charge and export figures below remain editable examples — enter your supplier quote.';calculate();$('#bill-lab').scrollIntoView({behavior:reduced()?'instant':'smooth',block:'start'});$('[data-bill="day"]').focus({preventScroll:true});track('tariff_rate_explored',{tariff:t.id});}));
}
if($('[data-tariff-results]')||$('[data-bill-form]'))initTariffs().catch(()=>{const output=$('[data-results-title]');if(output)output.textContent='Supplier examples · comparison controls are temporarily unavailable';});

async function initProducts(){
 const {PANELS,BATTERIES}=await import('/studio-src/catalogue.mjs');const products=[...BATTERIES.filter(p=>p.id!=='none'),...PANELS],selected=new Set();const status=$('[data-compare-status]');
 $$('[data-product-filter]').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.productFilter;let shown=0;$$('[data-product-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$$('[data-product-kind]').forEach(card=>{card.hidden=filter!=='all'&&card.dataset.productKind!==filter;if(!card.hidden)shown++;});$('[data-product-count]').textContent=shown+' products · choose up to 3 to compare';track('product_filter',{filter});}));
 const field=(p,k)=>k==='type'?p.watts?'Solar module':'Home battery':k==='output'?p.watts?p.watts+' W':p.usable+' kWh usable':k==='size'?`${Math.round((p.length||p.height)*1000)} × ${Math.round(p.width*1000)} × ${Math.round(p.depth*1000)} mm`:k==='warranty'?p.warranty:p.model;
 function renderCompare(){const output=$('[data-product-comparison]');output.hidden=!selected.size;if(!selected.size){status.textContent='Choose products from the same category for the most useful comparison.';return;}const ps=products.filter(p=>selected.has(p.id));const table=`<div class="t-table-wrap" tabindex="0" role="region" aria-label="Selected product comparison"><table class="t-table"><thead><tr><th scope="col">Specification</th>${ps.map(p=>`<th scope="col"><img src="${p.image}" width="100" height="110" alt="${esc(p.brand+' '+p.name)}"><br>${esc(p.name)}</th>`).join('')}</tr></thead><tbody>${[['type','Category'],['output','Rated output / usable storage'],['size','Height × width × depth'],['model','Exact model'],['warranty','Warranty · terms apply']].map(([key,label])=>`<tr><th scope="row">${label}</th>${ps.map(p=>`<td>${esc(field(p,key))}</td>`).join('')}</tr>`).join('')}<tr><th scope="row">Manufacturer reference</th>${ps.map(p=>`<td><a href="${p.source}" target="_blank" rel="noopener noreferrer">Open datasheet ↗</a></td>`).join('')}</tr></tbody></table></div>`;$('[data-comparison-table]').innerHTML=table;status.textContent=selected.size+' selected. Comparison is below the products. Battery stack images can show additional components; module dimensions exclude controllers and bases.';}
 $$('[data-compare-product]').forEach(input=>input.addEventListener('change',()=>{if(input.checked&&selected.size===3){input.checked=false;status.textContent='You can compare up to three products. Deselect one to add another.';return;}input.checked?selected.add(input.dataset.compareProduct):selected.delete(input.dataset.compareProduct);renderCompare();track('product_comparison',{products:[...selected]});}));
 $('[data-clear-compare]').addEventListener('click',()=>{selected.clear();$$('[data-compare-product]').forEach(el=>el.checked=false);renderCompare();$('[data-compare-product]')?.focus({preventScroll:true});});
}
if($('[data-products-grid]'))initProducts().catch(()=>{$('[data-compare-status]').textContent='The comparison controls are temporarily unavailable. Open a product page for its full specification.';});
