import test from 'node:test';import assert from 'node:assert/strict';
import {defaults,sanitise,faceGeometry,roofSlots,setPanelCount,reflowPanels,fits,energy,cost,recommendations,mountingZones,HOUSE_TEMPLATES} from '../studio-src/engine.mjs';
import {PANELS,BATTERIES,PRICEBOOK} from '../studio-src/catalogue.mjs';
import {sceneSvg,facePoint} from '../studio-src/scene.mjs';
import quoteHandler,{createQuote,sign,verify,liveConfig} from '../api/studio-quote.mjs';
import propertyHandler,{tableRows,propertyView} from '../api/studio-property.mjs';
const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(j){this.body=j;return this}});

test('All 4 houses × 4 roofs × 4 panels × 2 orientations retain non-overlapping roof slots',()=>{
 for(const house of Object.keys(HOUSE_TEMPLATES))for(const roof of ['gable','hip','flat','mono'])for(const brand of PANELS)for(const orientation of ['portrait','landscape']){
  const d=sanitise({...defaults(),...HOUSE_TEMPLATES[house],house,roof,panel:brand.id,orientation});
  for(const f of faceGeometry(d)){setPanelCount(d,f.id,100);for(const p of d.panels)assert.ok(fits(d,p,p.id),`${house}/${roof}/${brand.id}/${orientation}/${f.id}`);}
  for(const camera of ['front','rear'])assert.doesNotMatch(sceneSvg(d,'front','home',camera),/NaN|Infinity|undefined/);
 }
});
test('Narrow roofs, extreme pitches and template switching fail gracefully',()=>{
 for(const roof of ['gable','hip','mono','flat'])for(const pitch of [5,32,55])for(const width of [3,5,18]){
  const d=sanitise({...defaults(),width,depth:3,roof,pitch});setPanelCount(d,faceGeometry(d)[0].id,99);d.width=3;d.depth=3;d.roof='hip';reflowPanels(d);assert.ok(d.panels.every(p=>fits(d,p,p.id)));assert.ok(d.panels.length<=roofSlots(d,'front').length);
 }
});
test('Mono-pitch geometry is one complete plane with fixed high and low edges',()=>{const d={...defaults(),roof:'mono'},f=faceGeometry(d)[0];assert.equal(faceGeometry(d).length,1);const high=facePoint(f,0,f.length);assert.ok(Math.abs(high[2]+d.depth/2)<1e-9);assert.ok(Math.abs(high[1]-d.height-d.depth*Math.tan(d.pitch*Math.PI/180))<1e-9)});
test('Keep-clear zones exclude whole panel rectangles and remain excluded on reflow',()=>{const d=defaults();d.obstacles=[{face:'front',x:3,y:1,w:1,h:1.2}];setPanelCount(d,'front',50);assert.ok(d.panels.every(p=>fits(d,p,p.id)));d.panel='jinko';d.orientation='landscape';reflowPanels(d);assert.ok(d.panels.every(p=>fits(d,p,p.id)));});
test('Every battery is limited to candidate zones; images cannot intersect roof polygons',()=>{for(const b of BATTERIES)for(const house of Object.keys(HOUSE_TEMPLATES)){const d=sanitise({...defaults(),house,battery:b.id,modules:999,batteryZone:'anywhere',batteryPosition:999,hasGarage:false});assert.ok(!mountingZones(d).some(z=>z.id==='garage'));assert.equal(d.batteryZone,'exterior');assert.ok(d.modules<=b.max);assert.doesNotMatch(sceneSvg(d),/<image|<img|battery-node/);}});
test('Energy balances reconcile generation, demand, storage losses and export',()=>{for(const day of ['day','evening'])for(const load of [500,2400,8000,40000])for(const b of BATTERIES){const d=sanitise({...defaults(),annual:load,daytime:day,battery:b.id,modules:1});setPanelCount(d,'front',15);setPanelCount(d,'rear',8);const e=energy(d);assert.ok(Math.abs(e.annual-e.direct-e.charge-e.exported)<.001);assert.ok(Math.abs(load-e.direct-e.stored-e.remaining)<.001);assert.ok(e.stored<=e.capacity*365);assert.ok(e.solarFraction<=100);assert.equal(e.arbitrage,0);assert.equal(e.monthly.length,12);}});
test('Unfavourable off-peak spreads never invent a positive arbitrage return',()=>{const d={...defaults(),panels:[],importP:20,offpeakP:30};assert.equal(energy(d).arbitrage,0);d.offpeakP=7;assert.ok(energy(d).arbitrage>0);});
test('Recommendations respect solar-only, battery-only, installed battery and usable roof limits',()=>{for(const goal of ['solar','battery','both'])for(const existingBattery of [true,false]){const d={...defaults(),goal,existingBattery,width:3,depth:3};const opts=recommendations(d);assert.equal(opts.length,3);for(const o of opts){if(goal==='battery')assert.equal(o.design.panels.length,0);if(goal==='solar'||existingBattery)assert.equal(o.design.battery,'none');assert.ok(o.design.panels.every(p=>fits(o.design,p,p.id)));assert.equal(o.cost.total,cost(o.design).total);}}});
test('Manufacturer capacities, exact model names and local imagery are preserved',()=>{assert.equal(BATTERIES.find(b=>b.id==='sigen10').usable,8.76);assert.equal(BATTERIES.find(b=>b.id==='sigen6').usable,5.84);assert.equal(BATTERIES.find(b=>b.id==='dura16').usable,14.4);assert.equal(BATTERIES.find(b=>b.id==='tesla').nominal,null);for(const p of [...PANELS,...BATTERIES.filter(b=>b.id!=='none')]){assert.ok(p.source.startsWith('https://'));assert.ok(p.image.startsWith('/studio/assets/'));}});
test('Quote ignores a browser-supplied price and recalculates the server allowance',()=>{const d=defaults();setPanelCount(d,'front',10);const q=createQuote({...d,total:1,cost:{total:1}});assert.equal(q.cost.total,cost(d).total);assert.equal(q.mode,'demo');assert.equal(q.token,undefined);assert.throws(()=>createQuote({...d,panels:[],battery:'none'}),/Add solar/)});
test('Quote signatures reject price changes and expired tokens',()=>{const secret='x'.repeat(40),q={expires:new Date(Date.now()+100000).toISOString(),cost:{total:1234}};const token=sign(q,secret);assert.equal(verify(token,secret).cost.total,1234);assert.throws(()=>verify(token.replace(token.slice(-5),'wrong'),secret));assert.throws(()=>verify(sign({...q,expires:'2020-01-01'},secret),secret),/expired/);});
test('Preview branches cannot activate binding acceptance even with full production configuration',async()=>{const env={SUNWARD_LIVE_ACCEPTANCE:'true',SUNWARD_PRICEBOOK_APPROVED:'true',SUNWARD_CONTRACT_APPROVED:'true',SUNWARD_PRICEBOOK_JSON:JSON.stringify({...PRICEBOOK,productPrices:Object.fromEntries([...PANELS,...BATTERIES.filter(b=>b.id!=='none')].map(p=>[p.id,p.price]))}),SUNWARD_CONTRACT_JSON:JSON.stringify({version:'1',text:'Terms',companyName:'Test',companyAddress:'Test address',cancellationText:'Test',paymentText:'Test',complaintsContact:'Test'}),SUNWARD_ACCEPTANCE_URL:'https://orders.example.com/',SUNWARD_QUOTE_SECRET:'s'.repeat(40),SUNWARD_ACCEPTANCE_KEY:'test'};assert.ok(liveConfig(env));assert.equal(liveConfig({...env,VERCEL_ENV:'preview'}),null);assert.equal(liveConfig({...env,VERCEL_GIT_COMMIT_REF:'sunward-v2-preview'}),null);const res=response();await quoteHandler({method:'POST',headers:{host:'localhost'},body:{action:'accept'}},res);assert.equal(res.code,503);});
test('Property parser understands actual Searchland nested fields and blank dotted cells',()=>{const rows=tableRows({content:[{type:'text',text:JSON.stringify({total:1,results:'| id | address | total_number_of_addresses | is_listed_building | roof_information.roof_area_m2.value | roof_information | building_information |\n| --- | --- | --- | --- | --- | --- | --- |\n| public-building | Millmead House | 49 | true | | {"roof_shape":{"value":"Pitched"},"roof_area_m2":{"value":703.6,"extra_info":{"area_is_facing_east_m2":289.3}}} | {"number_of_floors":{"value":4}} |'})}]});const p=propertyView(rows[0],null,[],'Millmead');assert.equal(p.roofArea,703.6);assert.equal(p.orientationAreas.east,289.3);assert.equal(p.floors,4);assert.equal(p.addressCount,49);assert.equal(p.geometry,null);assert.equal(p.listed,true);assert.equal(tableRows({results:[{uprn:123,lat:51,lng:0}]}).length,1);});
test('Unavailable property credentials return manual mode before forwarding an address',async()=>{const res=response();await propertyHandler({method:'POST',headers:{host:'localhost'},body:{action:'lookup',address:'Test postcode',consent:true}},res);assert.equal(res.code,503);assert.match(res.body.message,/no address was sent/i)});
