// UK manufacturer specifications verified 7 September 2026. Prices are illustrative only.
export const VERSION="4.0.0";
export const PANELS=[
  {
    "id": "aiko",
    "brand": "AIKO",
    "name": "Neostar 2S all-black 460W",
    "model": "AIKO-A460-MAH54Mb",
    "watts": 460,
    "width": 1.134,
    "length": 1.757,
    "depth": 0.03,
    "price": 115,
    "colour": "#192526",
    "source": "https://aikosolar.com/wp-content/uploads/2025/10/Neostar-2S_188-AIKO-A-MAH54Mb_440-470W-1757x1134x30mm_V4.1_202510_DsDr_EN.pdf",
    "image": "/studio/assets/aiko-neostar2s.webp",
    "imageNote": "Manufacturer product artwork",
    "warranty": "25 / 30 years · terms apply",
    "verifiedOn": "2026-09-07"
  },
  {
    "id": "longi",
    "brand": "LONGi",
    "name": "Hi-MO X6 Scientist all-black 450W",
    "model": "LR5-54HTB-450M",
    "watts": 450,
    "width": 1.134,
    "length": 1.722,
    "depth": 0.03,
    "price": 105,
    "colour": "#20292b",
    "source": "https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F129_LR_5_54_HTB_440_450_M_V1_30_30_and_15_Frame_Scientist_V19_0860168025.pdf",
    "image": "/studio/assets/longi-himo-x6-450.webp",
    "imageNote": "Manufacturer product artwork",
    "warranty": "25 / 25 years · terms apply",
    "verifiedOn": "2026-09-07"
  },
  {
    "id": "dmegc",
    "brand": "DMEGC",
    "name": "N-type all-black double-glass 450W",
    "model": "DM450M10RT-B54HBB",
    "watts": 450,
    "width": 1.134,
    "length": 1.762,
    "depth": 0.03,
    "price": 90,
    "colour": "#213334",
    "source": "https://www.dmegcsolar.com/upload/img/2025-07/686350a164ddc.pdf",
    "image": "/studio/assets/dmegc-all-black.webp",
    "imageNote": "Manufacturer product artwork",
    "warranty": "25 / 30 years · terms apply",
    "verifiedOn": "2026-09-07"
  },
  {
    "id": "jinko",
    "brand": "Jinko Solar",
    "name": "Tiger Neo N-type all-black 440W",
    "model": "JKM440N-54HL4R-B",
    "watts": 440,
    "width": 1.134,
    "length": 1.762,
    "depth": 0.03,
    "price": 95,
    "colour": "#182d32",
    "source": "https://www.jinkosolar.com/uploads/JKM420-440N-54HL4R-B-F1.3-EN.pdf",
    "image": "/studio/assets/jinko-tiger-neo-440.webp",
    "imageNote": "Manufacturer product artwork",
    "warranty": "25 / 30 years · terms apply",
    "verifiedOn": "2026-09-07"
  }
];
export const BATTERIES=[
  {
    "id": "none",
    "brand": "Solar only",
    "name": "No battery",
    "usable": 0,
    "nominal": 0,
    "width": 0,
    "height": 0,
    "depth": 0,
    "price": 0,
    "max": 0,
    "source": ""
  },
  {
    "id": "tesla",
    "brand": "Tesla",
    "name": "Powerwall 3",
    "usable": 13.5,
    "nominal": null,
    "width": 0.609,
    "height": 1.105,
    "depth": 0.193,
    "price": 6500,
    "max": 4,
    "source": "https://energylibrary.tesla.com/docs/Public/EnergyStorage/Powerwall/3/Datasheet/en-uk/Powerwall-3-Datasheet-EN.pdf",
    "image": "/studio/assets/tesla-powerwall3.webp",
    "imageNote": "Manufacturer product artwork",
    "controller": "Integrated solar inverter and system controller",
    "mount": "wall / floor",
    "model": "1707000-xx-y",
    "warranty": "10 years · terms apply",
    "verifiedOn": "2026-09-07"
  },
  {
    "id": "sigen6",
    "brand": "Sigenergy",
    "name": "SigenStor BAT 6.0",
    "usable": 5.84,
    "nominal": 6.02,
    "width": 0.767,
    "height": 0.27,
    "depth": 0.265,
    "price": 2200,
    "max": 6,
    "controller": "Sigen Energy Controller required",
    "mount": "wall / floor",
    "image": "/studio/assets/sigenergy-sigenstor-system.webp",
    "source": "https://wwwstatic.sigenergy.com/content/assets/uploads/en_download/1746004583307009.pdf",
    "imageNote": "Representative SigenStor system with controller and multiple battery modules",
    "model": "SigenStor BAT 6.0",
    "warranty": "10 years · terms apply",
    "verifiedOn": "2026-09-07"
  },
  {
    "id": "sigen10",
    "brand": "Sigenergy",
    "name": "SigenStor BAT 10.0",
    "usable": 8.76,
    "nominal": 9.04,
    "width": 0.767,
    "height": 0.27,
    "depth": 0.265,
    "price": 2850,
    "max": 6,
    "controller": "Sigen Energy Controller required",
    "mount": "wall / floor",
    "image": "/studio/assets/sigenergy-sigenstor-system.webp",
    "source": "https://wwwstatic.sigenergy.com/content/assets/uploads/en_download/1746004583307009.pdf",
    "imageNote": "Representative SigenStor system with controller and multiple battery modules",
    "model": "SigenStor BAT 10.0",
    "warranty": "10 years · terms apply",
    "verifiedOn": "2026-09-07"
  },
  {
    "id": "dura16",
    "brand": "Duracell Energy",
    "name": "Dura16 LV",
    "usable": 14.4,
    "nominal": 16,
    "width": 0.52,
    "height": 0.86,
    "depth": 0.236,
    "price": 3600,
    "max": 1,
    "controller": "Compatible low-voltage inverter required",
    "mount": "wall",
    "source": "https://duracell.hacdn.io/media/documents/Dura16kWh_LV_Battery_Datasheet_v1.2_UK_web_PD.pdf",
    "image": "/studio/assets/duracell-dura16.webp",
    "imageNote": "Manufacturer product artwork",
    "model": "PD-16KWH-50V-1G",
    "warranty": "10 years · terms apply",
    "verifiedOn": "2026-09-07"
  }
];
export const PRICEBOOK={
  "version": "example-2026-09",
  "approved": false,
  "currency": "GBP",
  "solarBase": 2500,
  "panelLabour": 85,
  "scaffold": 750,
  "inverter": 1100,
  "sigenController": 1900,
  "duraInverter": 1400,
  "batteryLabour": 600,
  "backup": 1200,
  "bird": 350,
  "vatPercent": 0,
  "vatNote": "Illustration uses 0% VAT. Eligibility and final tax treatment must be checked before a live quote."
};
