import {PANELS,BATTERIES,PRICEBOOK} from './catalogue.mjs';
export const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number.isFinite(+n)?+n:min));
export const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
export const uuid=()=>globalThis.crypto?.randomUUID?.()||'d'+Date.now().toString(36)+Math.random().toString(36).slice(2);
export const defaults=()=>({v:4,night:false,priority:'bills',usageMode:'kwh',monthlySpend:110,existingSolar:false,existingBattery:false,existingKwp:0,batteryZone:'exterior',hasGarage:true,goal:'both',house:'detached',roof:'gable',width:9,depth:8,height:5.4,pitch:32,azimuth:180,setback:.4,gap:.025,shade:10,annual:4200,importP:25,exportP:12,offpeakP:7,daytime:'evening',ev:false,heatpump:false,owner:'owner',backup:false,bird:false,panel:'aiko',battery:'tesla',modules:1,batteryWall:'east',batteryPosition:.72,batteryHeight:.25,orientation:'portrait',faces:[],panels:[],obstacles:[],assumptions:true});
export function faceGeometry(d){
 const w=clamp(d.width,3,25),depth=clamp(d.depth,3,25),pitch=clamp(d.pitch,5,60)*Math.PI/180,h=clamp(d.height,2,12),rise=depth/2*Math.tan(pitch);
 if(d.roof==='flat')return [{id:'flat',label:'Flat roof',width:w,length:depth,azimuth:d.azimuth,pitch:10,origin:[-w/2,h,depth/2],u:[1,0,0],v:[0,0,-1],shape:[[0,0],[w,0],[w,depth],[0,depth]]}];
 if(d.roof==='mono')return [{id:'front',label:'Mono-pitch roof',width:w,length:depth/Math.cos(pitch),azimuth:d.azimuth,pitch:d.pitch,origin:[-w/2,h,depth/2],u:[1,0,0],v:[0,Math.sin(pitch),-Math.cos(pitch)],shape:[[0,0],[w,0],[w,depth/Math.cos(pitch)],[0,depth/Math.cos(pitch)]]}];
 const slope=depth/2/Math.cos(pitch),hip=d.roof==='hip'?Math.min(depth/2,w/3):0;
 const out=[{id:'front',label:'Front roof',width:w,length:slope,azimuth:d.azimuth,pitch:d.pitch,origin:[-w/2,h,depth/2],u:[1,0,0],v:[0,Math.sin(pitch),-Math.cos(pitch)],shape:[[0,0],[w,0],[w-hip,slope],[hip,slope]]},{id:'rear',label:'Rear roof',width:w,length:slope,azimuth:(d.azimuth+180)%360,pitch:d.pitch,origin:[w/2,h,-depth/2],u:[-1,0,0],v:[0,Math.sin(pitch),Math.cos(pitch)],shape:[[0,0],[w,0],[w-hip,slope],[hip,slope]]}];
 if(hip){const sideLen=Math.hypot(hip,rise),sa=Math.atan2(rise,hip);out.push({id:'east',label:'Right hip',width:depth,length:sideLen,azimuth:(d.azimuth+270)%360,pitch:sa*180/Math.PI,origin:[w/2,h,depth/2],u:[0,0,-1],v:[-Math.cos(sa),Math.sin(sa),0],shape:[[0,0],[depth,0],[depth/2,sideLen]]},{id:'west',label:'Left hip',width:depth,length:sideLen,azimuth:(d.azimuth+90)%360,pitch:sa*180/Math.PI,origin:[-w/2,h,-depth/2],u:[0,0,1],v:[Math.cos(sa),Math.sin(sa),0],shape:[[0,0],[depth,0],[depth/2,sideLen]]});}return out;
}
export function compass(n){return ['N','NE','E','SE','S','SW','W','NW'][Math.round(((n%360)+360)%360/45)%8];}
export function pointIn(p,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
function segmentDistance(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],t=clamp(((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy),0,1);return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);}
export function dimensions(panel){const p=PANELS.find(x=>x.id===panel.brand)||PANELS[0];return panel.landscape?{w:p.length,h:p.width}:{w:p.width,h:p.length};}
export function fits(d,p,ignoreId){const f=faceGeometry(d).find(x=>x.id===p.face);if(!f)return false;const {w,h}=dimensions(p),edge=clamp(d.setback,.2,1.5),corners=[[p.x,p.y],[p.x+w,p.y],[p.x+w,p.y+h],[p.x,p.y+h]];
 if(corners.some(c=>!pointIn(c,f.shape)||f.shape.some((a,i)=>segmentDistance(c,a,f.shape[(i+1)%f.shape.length])<edge-1e-6)))return false;
 const overlap=(a,b,g)=>a.x<b.x+b.w+g-1e-6&&a.x+a.w+g>b.x+1e-6&&a.y<b.y+b.h+g-1e-6&&a.y+a.h+g>b.y+1e-6;
 if((d.obstacles||[]).some(o=>o.face===p.face&&overlap({x:p.x,y:p.y,w,h},o,.3)))return false;
 if(d.panels.some(q=>q.id!==ignoreId&&q.face===p.face&&overlap({x:p.x,y:p.y,w,h},{x:q.x,y:q.y,...dimensions(q)},clamp(d.gap,.02,.1))))return false;
 return true;
}
export function addPanel(d,face,x,y,landscape=d.orientation==='landscape'){const p={id:uuid(),face,x:Math.round(x*1000)/1000,y:Math.round(y*1000)/1000,brand:d.panel,landscape};if(d.panels.length>=100||!fits(d,p))return false;d.panels.push(p);return true;}
export function autoFill(d,face){const f=faceGeometry(d).find(x=>x.id===face);if(!f)return;const s=clamp(d.setback,.2,1.5),p={brand:d.panel,landscape:d.orientation==='landscape'},size=dimensions(p),gap=d.roof==='flat'?.6:clamp(d.gap,.02,.1);for(let y=s+.001;y+size.h<f.length-s;y+=size.h+gap)for(let x=s+.001;x+size.w<f.width-s;x+=size.w+clamp(d.gap,.02,.1))addPanel(d,face,x,y,p.landscape);}
export function sanitise(input){const base=defaults(),d=Object.fromEntries(Object.keys(base).map(k=>[k,input&&Object.hasOwn(input,k)?input[k]:base[k]]));d.v=4;d.priority=['bills','payback','independence','backup','ev','generation'].includes(d.priority)?d.priority:'bills';d.usageMode=d.usageMode==='spend'?'spend':'kwh';d.monthlySpend=clamp(d.monthlySpend,15,1500);d.existingSolar=d.existingSolar===true;d.existingBattery=d.existingBattery===true;d.existingKwp=d.existingSolar?clamp(d.existingKwp,0,20):0;d.hasGarage=d.hasGarage===true;d.batteryZone=['exterior','garage','utility'].includes(d.batteryZone)?d.batteryZone:'exterior';if(!d.hasGarage&&d.batteryZone==='garage')d.batteryZone='exterior';d.goal=['solar','battery','both','unsure'].includes(d.goal)?d.goal:'both';d.house=['detached','semi','terrace','bungalow'].includes(d.house)?d.house:'detached';d.owner=['owner','tenant','leaseholder','other'].includes(d.owner)?d.owner:'other';d.daytime=d.daytime==='day'?'day':'evening';d.orientation=d.orientation==='landscape'?'landscape':'portrait';d.ev=d.ev===true;d.heatpump=d.heatpump===true;d.night=d.night===true;d.width=clamp(d.width,3,25);d.depth=clamp(d.depth,3,25);d.height=clamp(d.height,2,12);d.pitch=clamp(d.pitch,5,60);d.azimuth=clamp(d.azimuth,0,359);d.shade=clamp(d.shade,0,90);d.setback=clamp(d.setback,.2,1.5);d.gap=clamp(d.gap,.02,.1);d.annual=clamp(d.annual,500,40000);d.importP=clamp(d.importP,1,100);d.exportP=clamp(d.exportP,0,100);d.offpeakP=clamp(d.offpeakP,0,100);d.batteryHeight=clamp(d.batteryHeight,.1,1.8);d.batteryPosition=clamp(d.batteryPosition,.1,.9);d.batteryWall=['east','west','front','rear'].includes(d.batteryWall)?d.batteryWall:'east';d.roof=['gable','hip','flat','mono'].includes(d.roof)?d.roof:'gable';d.panel=PANELS.some(p=>p.id===d.panel)?d.panel:'aiko';d.battery=BATTERIES.some(p=>p.id===d.battery)?d.battery:'none';d.modules=d.battery==='none'?0:Math.round(clamp(d.modules,1,BATTERIES.find(p=>p.id===d.battery).max));d.backup=d.backup===true;d.bird=d.bird===true;d.obstacles=Array.isArray(d.obstacles)?d.obstacles.slice(0,30).filter(o=>Number.isFinite(o.x)&&Number.isFinite(o.y)&&Number.isFinite(o.w)&&Number.isFinite(o.h)&&o.w>0&&o.h>0).map(o=>({id:String(o.id).slice(0,60),face:String(o.face).slice(0,10),x:clamp(o.x,0,25),y:clamp(o.y,0,30),w:clamp(o.w,.1,25),h:clamp(o.h,.1,25)})):[];const panels=Array.isArray(d.panels)?d.panels.slice(0,100):[];d.panels=[];for(const p of panels){if(Number.isFinite(p.x)&&Number.isFinite(p.y)&&PANELS.some(x=>x.id===p.brand)&&fits(d,p))d.panels.push({id:String(p.id).slice(0,60),x:p.x,y:p.y,face:p.face,brand:p.brand,landscape:p.landscape===true});}return d;}
export function cost(d,book=PRICEBOOK){const counts={};for(const p of d.panels)counts[p.brand]=(counts[p.brand]||0)+1;const b=BATTERIES.find(b=>b.id===d.battery)||BATTERIES[0],items=[];const line=(id,label,q,unit)=>items.push({id,label,qty:q,unit,amount:q*unit});for(const [id,n]of Object.entries(counts)){const p=PANELS.find(x=>x.id===id);line(id,p.name,n,book.productPrices?.[id]??p.price);}if(d.panels.length){line('solarBase','Roof installation, cabling & commissioning',1,book.solarBase);line('mount','Mounting & module installation',d.panels.length,book.panelLabour);line('scaffold','Scaffolding allowance',1,book.scaffold);if(b.id==='none')line('inverter','Compatible solar inverter allowance',1,book.inverter);if(d.bird)line('bird','Bird protection allowance',1,book.bird);}if(b.id!=='none'){line(b.id,b.name,d.modules,book.productPrices?.[b.id]??b.price);line('batteryLabour','Battery installation allowance',1,book.batteryLabour);if(b.id.startsWith('sigen'))line('controller','Sigen Energy Controller allowance',1,book.sigenController);if(b.id==='dura16')line('duraInverter','Compatible Dura-i inverter allowance',1,book.duraInverter);if(d.backup)line('backup','Compatible backup gateway & circuits allowance',1,book.backup);}const net=items.reduce((a,x)=>a+x.amount,0),vat=Math.round(net*book.vatPercent)/100;return {items,net,vat,total:net+vat,book:book.version,approved:book.approved===true};}
export function energy(d){const fs=faceGeometry(d),b=BATTERIES.find(x=>x.id===d.battery)||BATTERIES[0];let kwp=0,annual=0;const byFace={};for(const p of d.panels){const m=PANELS.find(x=>x.id===p.brand),f=fs.find(x=>x.id===p.face);if(!m||!f)continue;const k=m.watts/1000,angle=Math.abs(((f.azimuth-180+540)%360)-180),factor=1-.45*(angle/180),tilt=1-Math.min(.15,Math.abs(f.pitch-32)*.004),y=k*950*factor*tilt*(1-d.shade/100);kwp+=k;annual+=y;byFace[f.id]=(byFace[f.id]||0)+y;}
 const existingGeneration=d.existingKwp*950*(1-d.shade/100);annual+=existingGeneration;const capacity=b.usable*d.modules;let direct=0,charge=0,stored=0,exported=0,remaining=0;
 const solarWeights=[.025,.045,.075,.10,.12,.13,.13,.12,.095,.075,.05,.035],loadWeights=[1.2,1.15,1.05,.95,.9,.85,.85,.9,.95,1.05,1.1,1.2],days=[31,28,31,30,31,30,31,31,30,31,30,31],ss=solarWeights.reduce((a,v)=>a+v,0),ls=loadWeights.reduce((a,v)=>a+v,0);
 const monthly=[];for(let i=0;i<12;i++){const generation=annual*solarWeights[i]/ss,load=d.annual*loadWeights[i]/ls,used=Math.min(load*(d.daytime==='day'?.65:.35),generation*(d.daytime==='day'?.65:.45)),input=Math.min(Math.max(generation-used,0),capacity*days[i],Math.max(load-used,0)/.9),out=input*.9;direct+=used;charge+=input;stored+=out;exported+=Math.max(generation-used-input,0);remaining+=Math.max(load-used-out,0);monthly.push({generation,load,direct:used,stored:out,exported:Math.max(generation-used-input,0),imported:Math.max(load-used-out,0)});}
 const arbitrage=annual===0?Math.min(remaining,capacity*280*.9)*Math.max(0,(d.importP-d.offpeakP/.9)/100):0,savings=(direct+stored)*d.importP/100+exported*d.exportP/100+arbitrage;return {kwp,existingGeneration,monthly,generationLow:annual*.85,generationHigh:annual*1.15,savingsLow:savings*.8,savingsHigh:savings*1.2,annual,direct,charge,stored,exported,remaining,capacity,arbitrage,savings,byFace,solarFraction:Math.min(100,(direct+stored)/d.annual*100)};}
export function advice(d,property=null){const a=[];if(property?.orientationAreas){const best=Object.entries(property.orientationAreas).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1])[0];if(best)a.push({level:'good',title:'Start with your recorded roof direction',text:'Available records show the largest roof-area share facing '+best[0].replaceAll('_','-')+'. This informs the template; usable panel space still needs confirmation.'});}if(d.owner!=='owner')a.push({level:'check',title:'Permission before panels',text:'A tenant, leaseholder or shared-roof owner needs the relevant owner/freeholder permissions. Your layout is a conversation starter, not consent.'});if(d.shade>20)a.push({level:'check',title:'Check the shade before the spend',text:'Your shading answer materially affects the result. Ask for a seasonal shading assessment; optimisers cannot recover sunlight that never reaches a module.'});if(d.daytime==='evening'&&d.battery!=='none')a.push({level:'good',title:'Save sunshine for when you get home',text:'Your evening-use pattern is a reason to compare storage with solar-only. Size it against actual overnight use, not the biggest battery available.'});if(d.ev||d.heatpump)a.push({level:'good',title:'Design around your electric future',text:'Include your expected EV and/or heat-pump use in annual kWh. The model does not add another allowance, avoiding double-counting.'});if(d.goal==='battery')a.push({level:'good',title:'Start with the tariff spread',text:'Battery-only value depends on cheap charging hours, round-trip losses and how much peak-rate electricity you actually replace.'});if(d.backup)a.push({level:'check',title:'Backup is a designed circuit',text:'A battery alone does not guarantee power during a cut. Gateway, earthing, load limits and protected circuits need an installer design.'});if(d.roof==='flat')a.push({level:'check',title:'Flat roof, different engineering',text:'The example uses extra row separation. Ballast, wind loading, waterproofing and shading require a site-specific design.'});if(property?.listed)a.push({level:'check',title:'Listed-building flag returned',text:'Searchland identifies a listed-building record. Obtain the appropriate specialist advice and permissions before installation.'});if(property?.constraints?.length)a.push({level:'check',title:'Local checks to make',text:'Records returned: '+property.constraints.join(', ')+'. Presence is not a decision on your proposed installation.'});a.push({level:'check',title:'An installer signs off the engineering',text:'Roof structure, wind zones, fire clearances, strings/MPPT, cable routes, battery siting and the grid connection remain survey checks.'});return a;}

// A constrained grid is the only way the Studio adds a new panel.
export function roofSlots(d,face){
 const clean={...d,panels:[]},f=faceGeometry(d).find(f=>f.id===face);if(!f)return [];
 const {w,h}=dimensions({brand:d.panel,landscape:d.orientation==='landscape'}),gap=clamp(d.gap,.02,.1),rowGap=d.roof==='flat'?.6:gap,edge=clamp(d.setback,.2,1.5)+.001;
 const slots=[];let row=0;for(let y=edge;y+h<f.length-edge;y+=h+rowGap,row++){let col=0;for(let x=edge;x+w<f.width-edge;x+=w+gap,col++){
  const p={id:`${face}-${row}-${col}`,face,x:+x.toFixed(3),y:+y.toFixed(3),brand:d.panel,landscape:d.orientation==='landscape'};if(fits(clean,p))slots.push(p);
 }}return slots;
}
export function setPanelCount(d,face,count){const slots=roofSlots(d,face);d.panels=d.panels.filter(p=>p.face!==face);d.panels.push(...slots.slice(0,Math.round(clamp(count,0,slots.length))));return d;}
export function reflowPanels(d,counts=null){const previous=counts||Object.fromEntries(faceGeometry(d).map(f=>[f.id,d.panels.filter(p=>p.face===f.id).length]));d.panels=[];for(const f of faceGeometry(d))setPanelCount(d,f.id,previous[f.id]||0);return d;}
export const HOUSE_TEMPLATES={detached:{name:'Detached',width:9,depth:8,height:5.4},semi:{name:'Semi-detached',width:6,depth:8,height:5.4},terrace:{name:'Terraced',width:5,depth:8,height:5.4},bungalow:{name:'Bungalow',width:10,depth:8,height:2.8}};
export const ROOF_TEMPLATES={gable:'Dual-pitch',hip:'Hip',flat:'Flat',mono:'Mono-pitch'};
export function mountingZones(d){return [{id:'exterior',name:d.house==='terrace'?'Rear exterior wall':'Exterior wall',note:'A sheltered, unobstructed wall. Installer checks openings, escape routes and clearances.'},...(d.hasGarage?[{id:'garage',name:'Garage',note:'A protected bay, clear of vehicles and escape routes. Fire and impact protection need checking.'}]:[]),{id:'utility',name:'Utility wall',note:'A candidate location only. Indoor battery siting needs a specific fire-safety and manufacturer review.'}];}
export function recommendations(input){
 const base=sanitise(input),f=faceGeometry(base).slice().sort((a,b)=>Math.abs(((a.azimuth-180+540)%360)-180)-Math.abs(((b.azimuth-180+540)%360)-180));
 return [{id:'good',label:'Good',title:'Keep it simple',sub:'A smaller first step',battery:base.goal==='solar'||base.existingBattery?'none':'sigen6',factor:.72,panel:'dmegc'},
 {id:'better',label:'Better',title:'Find your balance',sub:'Generation and useful storage',battery:base.goal==='solar'||base.existingBattery?'none':base.annual<3500?'sigen6':'sigen10',factor:1,panel:'aiko'},
 {id:'best',label:'Best',title:'Go further',sub:'More generation, more independence',battery:base.existingBattery?'none':base.goal==='solar'?'none':base.priority==='backup'?'tesla':base.annual>6500?'dura16':'tesla',factor:1.3,panel:'aiko'}].map(p=>{
 const d={...base,panels:[],panel:p.panel,battery:p.battery,modules:p.battery==='none'?0:1};if(base.goal!=='battery'){
 let target=Math.max(4,Math.round(base.annual/850/(PANELS.find(x=>x.id===p.panel).watts/1000)*p.factor));
 for(const face of f){if(target<=0)break;const n=Math.min(target,roofSlots(d,face.id).length);setPanelCount(d,face.id,n);target-=n;}
 }d.backup=base.backup&&d.battery!=='none';return {...p,design:sanitise(d),energy:energy(d),cost:cost(d)};
 });
}
