import {PANELS,BATTERIES,PRICEBOOK} from '/studio-src/catalogue.mjs';
import {defaults,sanitise,faceGeometry,addPanel,autoFill,cost,energy,advice,money,compass} from '/studio-src/engine.mjs';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE='sunward-studio-v3';
let design=sanitise(load()?.design||defaults()), property=load()?.property||null, quizIndex=load()?.quizIndex||0, view=load()?.view||'discover', tool='panels', camera=-28, history=[];
let quoteConfig={liveAcceptance:false,examplePricing:true,pricebook:PRICEBOOK}, currentQuote=null, propertyReady=false;
const quiz=[
 {key:'goal',title:'What do you want your home to do?',sub:'This changes the system we prioritise.',choices:[['both','Generate & store','Solar + battery, balanced together'],['solar','Generate more','Prioritise roof generation'],['battery','Shift my energy','Charge cheap, use later']]},
 {key:'annual',title:'Roughly how much electricity do you use?',sub:'Use your latest bill if you know it.',choices:[['2400','Low','1–2 people · ~2,400 kWh'],['3800','Typical','2–4 people · ~3,800 kWh'],['5500','High','Larger home · ~5,500 kWh'],['8000','Very high','EV / heat pump · 8,000+ kWh']]},
 {key:'daytime',title:'When does your home use most electricity?',sub:'It helps us explain solar-only versus storage.',choices:[['day','During the day','Home-working, appliances, daytime loads'],['evening','Evenings & overnight','Most demand after solar production falls']]},
 {key:'future',title:'Any big electrical loads now or soon?',sub:'We won’t secretly inflate your usage; this is for contextual advice.',multi:true,choices:[['ev','Electric car','Home charging'],['heatpump','Heat pump','Electric heating'],['none','Neither','Keep things simple']]},
 {key:'owner',title:'What’s your relationship with the property?',sub:'This changes the permissions advice, not the sales pitch.',choices:[['owner','I own it','Freeholder / homeowner'],['leaseholder','Leasehold','May need freeholder permission'],['tenant','I rent','Landlord permission needed'],['other','Other / shared','We’ll flag what to check']]}
];

function load(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')}catch{return null}}
function save(){localStorage.setItem(STORAGE,JSON.stringify({design,property,quizIndex,view}));$('#saveState').textContent='Design saved on this device'}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400)}
function pushHistory(){history.push(JSON.stringify(design));if(history.length>30)history.shift()}
function go(name){if(!['discover','property','design','system','quote'].includes(name))return;view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('[data-step]').forEach(b=>b.classList.toggle('active',b.dataset.step===name));window.scrollTo({top:0,behavior:'smooth'});save();if(name==='quote')refreshQuote();if(name==='design')renderScene()}
$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.jump)));$$('[data-step]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.step)));

function renderQuiz(){const q=quiz[quizIndex],host=$('#quizHost');$('#quizCount').textContent=`${quizIndex+1} of ${quiz.length}`;$('#quizBar').style.width=`${(quizIndex+1)/quiz.length*100}%`;
 const selected=(v)=>q.key==='future'?(v==='ev'?design.ev:v==='heatpump'?design.heatpump:!design.ev&&!design.heatpump):String(design[q.key])===String(v);
 host.innerHTML=`<div class="quiz-question"><div><span class="eyebrow">A FEW SMART QUESTIONS</span><h2>${q.title}</h2><p class="muted">${q.sub}</p></div><div class="choice-grid">${q.choices.map(([v,l,s])=>`<button class="choice ${selected(v)?'selected':''}" data-qvalue="${v}"><strong>${l}</strong><small>${s}</small></button>`).join('')}</div><div class="quiz-footer"><button class="ghost" id="quizBack" ${quizIndex?'':'disabled'}>← Back</button><button class="primary" id="quizNext">${quizIndex===quiz.length-1?'Build my property model →':'Next →'}</button></div></div>`;
 $$('[data-qvalue]',host).forEach(btn=>btn.addEventListener('click',()=>{const v=btn.dataset.qvalue;if(q.key==='annual')design.annual=+v;else if(q.key==='future'){if(v==='none'){design.ev=false;design.heatpump=false}else{design[v]=!design[v]} }else design[q.key]=v;renderQuiz();updateAll()}));
 $('#quizBack').addEventListener('click',()=>{if(quizIndex){quizIndex--;renderQuiz();save()}});$('#quizNext').addEventListener('click',()=>{if(quizIndex<quiz.length-1){quizIndex++;renderQuiz();save()}else go('property')});
}

async function checkPropertyProvider(){try{const r=await fetch('/api/studio-property',{cache:'no-store'});const j=await r.json();propertyReady=Boolean(j.ready);$('#providerNote').textContent=propertyReady?'Searchland property intelligence is available. We’ll ask before sending the address.':'Live Searchland lookup is not configured in this preview. Manual modelling remains fully available.'}catch{propertyReady=false}}
$('#lookupBtn').addEventListener('click',async()=>{const address=$('#addressInput').value.trim();if(address.length<4)return toast('Enter an address or postcode first');if(!propertyReady)return toast('Searchland lookup is not enabled on this preview yet');$('#lookupBtn').disabled=true;$('#lookupBtn').textContent='Searching…';try{const r=await fetch('/api/studio-property',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'lookup',address,consent:true})}),j=await r.json();if(!r.ok)throw Error(j.message);const host=$('#addressResults');host.innerHTML=j.results?.length?j.results.map((x,i)=>`<button class="address-result" data-uprn="${x.uprn}">${x.address}</button>`).join(''):'No exact property match returned.';$$('[data-uprn]',host).forEach(b=>b.addEventListener('click',()=>loadProperty(b.dataset.uprn,b.textContent)))}catch(e){toast(e.message||'Property lookup failed')}finally{$('#lookupBtn').disabled=false;$('#lookupBtn').textContent='Find my home'}});
$('#manualProperty').addEventListener('click',()=>go('property'));
async function loadProperty(uprn,address){$('#addressResults').innerHTML='<div class="provider-note">Building your property context…</div>';try{const r=await fetch('/api/studio-property',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'property',uprn,consent:true})}),j=await r.json();if(!r.ok)throw Error(j.message);property=j.property;applyProperty(property);save();go('property');toast('Property records added to your model')}catch(e){toast(e.message||'Property data unavailable');go('property')}}
function applyProperty(p){if(!p)return;if(p.roofShape){const s=p.roofShape.toLowerCase();design.roof=s.includes('flat')?'flat':s.includes('hip')?'hip':'gable'}if(p.buildingHeight)design.height=Math.max(2,Math.min(12,+p.buildingHeight*.72));if(p.orientationAreas&&Object.keys(p.orientationAreas).length){const map={north:0,north_east:45,east:90,south_east:135,south:180,south_west:225,west:270,north_west:315};const best=Object.entries(p.orientationAreas).sort((a,b)=>b[1]-a[1])[0];if(best)design.azimuth=map[best[0]]??design.azimuth}if(p.roofArea){const footprint=Math.max(12,p.roofArea*(design.roof==='flat'?1:.78));const ratio=design.width/design.depth||1.1;design.width=Math.min(18,Math.max(3,Math.sqrt(footprint*ratio)));design.depth=Math.min(18,Math.max(3,footprint/design.width))}renderProperty();updateAll()}

function renderProperty(){const facts=[];const add=(k,v)=>facts.push(`<div class="fact"><span>${k}</span><b>${v??'Not returned'}</b></div>`);if(property){$('#propertyTitle').textContent='We found context for your property.';$('#propertySub').textContent=property.address;$('#propertySource').textContent='Searchland';$('#modelLabel').textContent='Searchland-informed model';$('#modelStatus').textContent='Correct anything that looks wrong';add('Roof area',property.roofArea?`${Math.round(property.roofArea)} m²`:'Not returned');add('Roof type',property.roofShape);add('Roof material',property.roofMaterial);add('Building height',property.buildingHeight?`${property.buildingHeight} m`:'Not returned');add('Floors',property.floors);add('EPC',property.epc?.rating||'Not returned');const c=$('#constraintNotice');if(property.listed||property.constraints?.length){c.classList.remove('hidden');c.textContent=[property.listed?'Listed-building flag returned.':'',property.constraints?.length?`Planning records: ${property.constraints.join(', ')}.`:''].filter(Boolean).join(' ')}else c.classList.add('hidden')}else{$('#propertyTitle').textContent='Let’s model your home.';$('#propertySub').textContent='Use the controls below to make the model feel like your property.';$('#propertySource').textContent='Manual';$('#modelLabel').textContent='Sunward model';$('#modelStatus').textContent='Built from your answers';add('House type',cap(design.house));add('Roof type',cap(design.roof));add('Main roof face',compass(design.azimuth));add('Annual electricity',`${design.annual.toLocaleString()} kWh`)}$('#propertyFacts').innerHTML=facts.join('');$('#sceneProperty').textContent=property?.address||'Manual property model';$('#quotePropertyName').textContent=property?.address||'Your property';renderMiniHouse()}
function cap(s){return String(s||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function renderMiniHouse(){$('#miniHouse').innerHTML=`<div style="height:100%;display:grid;place-items:center"><div style="width:62%;aspect-ratio:1.35;background:#dfd5c4;position:relative;box-shadow:0 20px 35px #52625622"><div style="position:absolute;left:-6%;right:-6%;top:-35%;height:42%;background:#554e47;clip-path:polygon(0 100%,50% 0,100% 100%)"></div><div style="position:absolute;left:14%;top:34%;width:18%;height:30%;background:#a6c0ba"></div><div style="position:absolute;right:14%;top:34%;width:18%;height:30%;background:#a6c0ba"></div><div style="position:absolute;left:44%;bottom:0;width:13%;height:38%;background:#31473e"></div></div></div>`}

const bind=(id,key,parse=v=>v)=>{$(id).addEventListener('input',e=>{pushHistory();design[key]=parse(e.target.value);if(['width','depth','pitch','azimuth'].includes(key))design.panels=[];syncControls();updateAll()})};
bind('#houseType','house');bind('#roofType','roof');bind('#widthRange','width',Number);bind('#depthRange','depth',Number);bind('#pitchRange','pitch',Number);bind('#azimuthRange','azimuth',Number);
function syncControls(){for(const [id,k] of [['#houseType','house'],['#roofType','roof'],['#widthRange','width'],['#depthRange','depth'],['#pitchRange','pitch'],['#azimuthRange','azimuth']])$(id).value=design[k];$('#widthOut').textContent=design.width.toFixed(1)+'m';$('#depthOut').textContent=design.depth.toFixed(1)+'m';$('#pitchOut').textContent=Math.round(design.pitch)+'°';$('#azimuthOut').textContent=compass(design.azimuth);$('#batteryQty').value=Math.max(1,design.modules);$('#batteryWall').value=design.batteryWall;$('#batteryPosition').value=Math.round(design.batteryPosition*100);$('#backupToggle').checked=design.backup;$('#birdToggle').checked=design.bird;}

function populateSelectors(){$('#panelSelect').innerHTML=PANELS.map(p=>`<option value="${p.id}">${p.brand} · ${p.watts}W</option>`).join('');$('#panelSelect').value=design.panel;$('#batterySelect').innerHTML=BATTERIES.map(b=>`<option value="${b.id}">${b.brand} · ${b.name}</option>`).join('');$('#batterySelect').value=design.battery;refreshFaces()}
function refreshFaces(){const fs=faceGeometry(design);$('#faceSelect').innerHTML=fs.map(f=>`<option value="${f.id}">${f.label} · ${compass(f.azimuth)}</option>`).join('');if(!fs.some(f=>f.id===$('#faceSelect').value))$('#faceSelect').value=fs[0]?.id||'front'}
$('#panelSelect').addEventListener('change',e=>{design.panel=e.target.value;updateAll()});$('#batterySelect').addEventListener('change',e=>{pushHistory();design.battery=e.target.value;design.modules=e.target.value==='none'?0:Math.max(1,design.modules);syncControls();updateAll()});$('#batteryQty').addEventListener('input',e=>{const b=BATTERIES.find(x=>x.id===design.battery)||BATTERIES[0];design.modules=design.battery==='none'?0:Math.max(1,Math.min(b.max,+e.target.value||1));updateAll()});$('#batteryWall').addEventListener('change',e=>{design.batteryWall=e.target.value;renderScene();save()});$('#batteryPosition').addEventListener('input',e=>{design.batteryPosition=+e.target.value/100;renderScene();save()});
$('#portraitBtn').addEventListener('click',()=>{design.orientation='portrait';$('#portraitBtn').classList.add('active');$('#landscapeBtn').classList.remove('active')});$('#landscapeBtn').addEventListener('click',()=>{design.orientation='landscape';$('#landscapeBtn').classList.add('active');$('#portraitBtn').classList.remove('active')});
$$('[data-tool]').forEach(b=>b.addEventListener('click',()=>{tool=b.dataset.tool;$$('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));$('#panelTools').classList.toggle('hidden',tool!=='panels');$('#batteryTools').classList.toggle('hidden',tool!=='battery');$('#obstacleTools').classList.toggle('hidden',tool!=='obstacle')}));
$('#autoFillBtn').addEventListener('click',()=>{pushHistory();const face=$('#faceSelect').value;design.panels=design.panels.filter(p=>p.face!==face);autoFill(design,face);updateAll();toast(`${design.panels.filter(p=>p.face===face).length} panels fitted on ${face} roof`)});$('#clearPanels').addEventListener('click',()=>{pushHistory();design.panels=[];updateAll()});$('#undoBtn').addEventListener('click',()=>{const last=history.pop();if(last){design=sanitise(JSON.parse(last));syncControls();populateSelectors();updateAll()}});$('#addObstacle').addEventListener('click',()=>{pushHistory();const f=$('#faceSelect').value;design.obstacles.push({id:'o'+Date.now(),face:f,x:design.width*.34,y:1,w:1,h:1.1});updateAll();toast('Keep-clear zone added — drag editing comes after measured geometry')});
$('#rotateLeft').addEventListener('click',()=>{camera-=22;renderScene()});$('#rotateRight').addEventListener('click',()=>{camera+=22;renderScene()});$('#resetCamera').addEventListener('click',()=>{camera=-28;renderScene()});

function renderScene(){const fs=faceGeometry(design),active=$('#faceSelect').value||fs[0]?.id;const h=$('#scene');const faceHtml=fs.map(f=>`<div class="roof-face ${f.id} ${active===f.id?'active':''}" data-face="${f.id}">${renderPanels(f)}${renderObstacles(f)}</div>`).join('');const b=BATTERIES.find(x=>x.id===design.battery)||BATTERIES[0];const batteries=b.id==='none'?'':Array.from({length:design.modules},(_,i)=>`<div class="battery-node" style="left:${design.batteryWall==='west'?18:design.batteryWall==='east'?76:46+i*4}%;top:${55+i*3}%;width:${Math.max(18,b.width*42)}px;height:${Math.max(30,b.height*52)}px">${b.brand}</div>`).join('');h.innerHTML=`<div class="house3d ${design.roof}" style="--rot:${camera}deg"><div class="ground-shadow"></div><div class="building-base"></div>${faceHtml}${batteries}</div>`;$$('.roof-face',h).forEach(el=>el.addEventListener('click',e=>{if(tool!=='panels')return;const f=fs.find(x=>x.id===el.dataset.face);if(!f)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*f.width,y=(e.clientY-r.top)/r.height*f.length;pushHistory();if(addPanel(design,f.id,x,y)){refreshFaces();updateAll()}else toast('That panel would cross a setback, obstacle or another panel')}));const valid=design.panels.length?`${design.panels.length} panels placed across ${new Set(design.panels.map(p=>p.face)).size} roof face${new Set(design.panels.map(p=>p.face)).size===1?'':'s'}`:'Tap a highlighted roof face to add panels';$('#designValidation').textContent=valid}
function renderPanels(f){return design.panels.filter(p=>p.face===f.id).map(p=>{const m=PANELS.find(x=>x.id===p.brand),w=p.landscape?m.length:m.width,h=p.landscape?m.width:m.length;return `<span class="panel-node" style="left:${p.x/f.width*100}%;top:${p.y/f.length*100}%;width:${w/f.width*100}%;height:${h/f.length*100}%"></span>`}).join('')}
function renderObstacles(f){return design.obstacles.filter(o=>o.face===f.id).map(o=>`<span class="keep-clear" style="left:${o.x/f.width*100}%;top:${o.y/f.length*100}%;width:${o.w/f.width*100}%;height:${o.h/f.length*100}%"></span>`).join('')}

function renderCatalogues(){const product=(p,type)=>`<article class="product-card ${design[type]===p.id?'selected':''}" data-${type}="${p.id}"><div class="product-media">${p.image?`<img src="${p.image}" alt="${p.brand} ${p.name}" loading="lazy" referrerpolicy="no-referrer">`:`<div class="product-placeholder">${p.brand}</div>`}</div><div class="product-body"><span class="eyebrow">${p.brand}</span><h3>${p.name}</h3><p>${type==='panel'?`${p.model} · ${p.watts}W module`:`${p.nominal||0} kWh nominal · ${p.usable||0} kWh usable`}</p><div class="specs">${type==='panel'?`<span>${p.length.toFixed(3)} × ${p.width.toFixed(3)}m</span><span>${p.watts}W</span>`:`<span>${p.mount||'—'} mounted</span><span>${p.usable||0} kWh usable</span>`}</div><div class="product-source"><a href="${p.source||'#'}" target="_blank" rel="noopener">Product source ↗</a><button>${design[type]===p.id?'Selected':'Choose'}</button></div></div></article>`;
 $('#panelCatalogue').innerHTML=PANELS.map(p=>product(p,'panel')).join('');$('#batteryCatalogue').innerHTML=BATTERIES.filter(b=>b.id!=='none').map(b=>product(b,'battery')).join('');$('#panelCountLabel').textContent=`${design.panels.length} panel${design.panels.length===1?'':'s'} on roof`;$$('[data-panel]').forEach(c=>c.addEventListener('click',()=>{const id=c.dataset.panel;pushHistory();design.panel=id;design.panels=design.panels.map(p=>({...p,brand:id}));design=sanitise(design);populateSelectors();updateAll();toast(`${PANELS.find(p=>p.id===id).brand} selected`)}));$$('[data-battery]').forEach(c=>c.addEventListener('click',()=>{design.battery=c.dataset.battery;design.modules=Math.max(1,design.modules);populateSelectors();updateAll();toast(`${BATTERIES.find(b=>b.id===design.battery).name} selected`)}))}
$('#backupToggle').addEventListener('change',e=>{design.backup=e.target.checked;updateAll()});$('#birdToggle').addEventListener('change',e=>{design.bird=e.target.checked;updateAll()});

async function fetchQuoteConfig(){try{const r=await fetch('/api/studio-quote',{cache:'no-store'}),j=await r.json();if(r.ok)quoteConfig=j}catch{}$('#liveMode').textContent=quoteConfig.liveAcceptance?'Live':'Preview';$('#acceptTitle').textContent=quoteConfig.liveAcceptance?'Accept this quote':'Save this design';$('#acceptBtn').textContent=quoteConfig.liveAcceptance?'Accept quote':'Create my quote';$('#acceptLegal').textContent=quoteConfig.liveAcceptance?'Acceptance is recorded only after the configured order service returns a durable receipt.':'Preview mode does not create a binding order or payment obligation.'}
async function refreshQuote(){const local=cost(design,quoteConfig.pricebook||PRICEBOOK),en=energy(design);renderQuote(local,en);try{const r=await fetch('/api/studio-quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'quote',design,project:{address:property?.address||''}})}),j=await r.json();if(r.ok&&j.quote){currentQuote=j.quote;renderQuote(j.quote.cost,j.quote.energy);$('#quoteTerms').textContent=j.quote.terms;$('#pricebookChip').textContent=j.quote.cost.approved?'Approved '+j.quote.cost.book:'Preview '+j.quote.cost.book;save()}}catch{}}
function renderQuote(c,en){const b=BATTERIES.find(x=>x.id===design.battery)||BATTERIES[0];$('#quoteSystemName').textContent=`${en.kwp.toFixed(2)} kWp solar${b.id!=='none'?` + ${(b.usable*design.modules).toFixed(1)} kWh storage`:''}`;$('#quoteTotal').textContent=$('#lineTotal').textContent=money(c.total);$('#quoteMode').textContent=c.approved?'Approved pricebook':'Example pricing';$('#quoteMetrics').innerHTML=[['Solar',en.kwp.toFixed(2)+' kWp'],['Storage',en.capacity.toFixed(1)+' kWh'],['Generation',Math.round(en.annual).toLocaleString()+' kWh/yr'],['Indicative saving',money(en.savings)+'/yr']].map(([a,b])=>`<div class="metric"><span>${a}</span><b>${b}</b></div>`).join('');$('#lineItems').innerHTML=c.items.length?c.items.map(i=>`<div class="line"><div><b>${i.label}</b><small>${i.qty>1?`${i.qty} × ${money(i.unit)}`:'Allowance'}</small></div><b>${money(i.amount)}</b></div>`).join(''):'<p class="muted">Add a panel or battery to create an itemised system.</p>';$('#adviceList').innerHTML=advice(design,property).map(a=>`<div class="advice-item"><span class="advice-icon">${a.level==='good'?'✓':'!'}</span><div><b>${a.title}</b><p>${a.text}</p></div></div>`).join('')}
$('#acceptBtn').addEventListener('click',async()=>{if(!currentQuote)await refreshQuote();if(!currentQuote)return toast('Build a system first');const receipt=$('#receipt');if(!quoteConfig.liveAcceptance){receipt.classList.remove('hidden');receipt.innerHTML=`<b>Design quote created</b><br>${currentQuote.id}<br><small>This is a non-binding preview record. No order has been placed.</small>`;toast('Preview quote created');return}const name=$('#customerName').value.trim(),email=$('#customerEmail').value.trim();if(!$('#scopeAgree').checked||!$('#termsAgree').checked)return toast('Review and tick both confirmations first');try{const r=await fetch('/api/studio-quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'accept',token:currentQuote.token,customer:{name,email},consent:{scope:true,terms:true}})}),j=await r.json();if(!r.ok)throw Error(j.message);receipt.classList.remove('hidden');receipt.innerHTML=`<b>Quote accepted</b><br>Receipt ${j.receipt.id}<br>${new Date(j.receipt.acceptedAt).toLocaleString('en-GB')}`;toast('Acceptance recorded')}catch(e){toast(e.message||'Quote acceptance could not be recorded')}});

function updateSidebar(){const en=energy(design),c=cost(design,quoteConfig.pricebook||PRICEBOOK);$('#sideKwp').textContent=en.kwp.toFixed(2);$('#sidePanels').textContent=design.panels.length;$('#sideStorage').textContent=en.capacity.toFixed(1)+' kWh';$('#sideGeneration').textContent=Math.round(en.annual).toLocaleString()+' kWh';$('#sideSaving').textContent=money(en.savings)+'/yr';$('#sideTotal').textContent=money(c.total);let conf=35;if(property)conf+=25;if(design.panels.length)conf+=20;if(design.annual>500)conf+=10;if(design.obstacles.length)conf+=5;conf=Math.min(95,conf);$('#confidenceBar').style.width=conf+'%';$('#confidenceText').textContent=property?`${conf}% planning confidence · survey still required`:'Add property records to improve context'}
function updateAll(){design=sanitise(design);syncControls();refreshFaces();renderProperty();renderScene();renderCatalogues();updateSidebar();save()}

$('#resetBtn').addEventListener('click',()=>{if(!confirm('Clear this Sunward design and start again?'))return;localStorage.removeItem(STORAGE);design=defaults();property=null;quizIndex=0;currentQuote=null;renderQuiz();populateSelectors();updateAll();go('discover')});

async function init(){renderQuiz();populateSelectors();syncControls();renderProperty();renderScene();renderCatalogues();await Promise.all([checkPropertyProvider(),fetchQuoteConfig()]);updateSidebar();go(view);if(view==='quote')refreshQuote()}
init();
