/* Progressive map: local public-domain outline + approximate guide markers;
   authoritative ONS upper-tier boundaries when the optional layer is available. */
(() => {'use strict';
const root=document.querySelector('[data-uk-map]');if(!root)return;
const $=s=>root.querySelector(s),svg=$('.uk-map'),geo=$('.map-geometry'),pins=$('.map-pins'),search=$('#county-search'),results=$('#county-results'),note=$('.map-data-note'),tooltip=$('.map-tooltip');
const ns='http://www.w3.org/2000/svg';let areas=[],records=[],features=[],nation='all',selected='',view=[0,0,600,660],hasBoundaries=false;
const norm=s=>String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const project=([lon,lat])=>[300+(lon+3.5)*32,30+(61-lat)*56];
const shape=(name,attrs={})=>{const e=document.createElementNS(ns,name);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));return e;};
const line=ring=>ring.map((p,i)=>(i?'L':'M')+project(p).map(n=>n.toFixed(2)).join(',')).join('')+'Z';
const nationSlug=n=>n.toLowerCase().replaceAll(' ','-');
const nationFor=code=>({E:'England',S:'Scotland',W:'Wales',N:'Northern Ireland'})[String(code)[0]]||'England';
const areaAlias={'East Riding of Yorkshire':'East Yorkshire','Durham':'County Durham','County of Herefordshire':'Herefordshire','Bath and North East Somerset':'Somerset','North Somerset':'Somerset','Bournemouth, Christchurch and Poole':'Dorset','Brighton and Hove':'East Sussex','Cumberland':'Cumbria','Westmorland and Furness':'Cumbria','York':'North Yorkshire','North Northamptonshire':'Northamptonshire','West Northamptonshire':'Northamptonshire','West Berkshire':'Berkshire','Reading':'Berkshire','Wokingham':'Berkshire','Windsor and Maidenhead':'Berkshire','Slough':'Berkshire','Bracknell Forest':'Berkshire','Plymouth':'Devon','Torbay':'Devon','Portsmouth':'Hampshire','Southampton':'Hampshire','Milton Keynes':'Buckinghamshire','Peterborough':'Cambridgeshire','Luton':'Bedfordshire','Central Bedfordshire':'Bedfordshire','Bedford':'Bedfordshire','Cheshire East':'Cheshire','Cheshire West and Chester':'Cheshire','Warrington':'Cheshire','Halton':'Cheshire','Blackburn with Darwen':'Lancashire','Blackpool':'Lancashire','Derby':'Derbyshire','Leicester':'Leicestershire','Nottingham':'Nottinghamshire','Southend-on-Sea':'Essex','Thurrock':'Essex','Stoke-on-Trent':'Staffordshire','Swindon':'Wiltshire','Telford and Wrekin':'Shropshire','Kingston upon Hull, City of':'East Yorkshire','Herefordshire, County of':'Herefordshire'};
function guideFor(name,code){if(String(code).startsWith('E09'))return areas.find(a=>a.name==='Greater London');return areas.find(a=>norm(a.name)===norm(areaAlias[name]||name));}
function makeRecord(name,nat,guide){return {name,nation:nat,url:guide?.url||'/locations/'+nationSlug(nat)+'/',towns:guide?.towns||[],count:guide?.count||0,wider:guide?guide.name!==name:true,guideName:guide?.name||nat};}
function setView(v){view=v;svg.setAttribute('viewBox',v.join(' '));}
function zoomFit(nodes){const b=[];nodes.forEach(n=>{try{const r=n.getBBox();if(r.width+r.height>0)b.push([r.x,r.y,r.x+r.width,r.y+r.height]);}catch{}});if(!b.length)return;let x=Math.min(...b.map(a=>a[0])),y=Math.min(...b.map(a=>a[1])),w=Math.max(...b.map(a=>a[2]))-x,h=Math.max(...b.map(a=>a[3]))-y;w+=55;h+=55;x-=27.5;y-=27.5;const ratio=600/660;if(w/h>ratio){const nh=w/ratio;y-=(nh-h)/2;h=nh;}else{const nw=h*ratio;x-=(nw-w)/2;w=nw;}setView([x,y,w,h]);}
function choose(rec,focusPanel=false){selected=rec.name;root.querySelectorAll('[data-area-name]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.areaName===rec.name)));$('[data-area-nation]').textContent=rec.nation.toUpperCase();$('[data-area-title]').textContent=rec.name;$('[data-area-copy]').textContent=rec.count?`Explore ${rec.count} local place guides${rec.wider?' in the wider '+rec.guideName+' area':''}. Then start an example enquiry with this area already selected.`:'Explore the wider nation directory, or start an example enquiry for this council area. Local installation availability still needs confirmation.';const t=$('[data-area-towns]');t.replaceChildren();rec.towns.slice(0,6).forEach(town=>{const a=document.createElement('a');a.href=town.url;a.textContent=town.name;t.append(a);});$('[data-area-guide]').href=rec.url;$('[data-area-guide]').firstChild.textContent=rec.wider?'Explore wider area guides ':'Explore local guides ';const q=new URLSearchParams({quote:'1',location:rec.name,interest:'both'});if(window.SunwardState?.product)q.set('product',window.SunwardState.product);$('[data-area-plan]').href='/?'+q;$('[data-area-plan]').firstChild.textContent='Start a plan in '+rec.name+' ';$('.area-actions').hidden=false;window.SunwardState=Object.assign(window.SunwardState||{},{area:rec.name});document.dispatchEvent(new Event('sunward:area'));if(focusPanel){$('[data-area-title]').setAttribute('tabindex','-1');$('[data-area-title]').focus({preventScroll:true});}}
function list(){const q=norm(search.value);const visible=records.filter(a=>(nation==='all'||a.nation===nation)&&(!q||norm(a.name).includes(q)||a.towns.some(t=>norm(t.name).includes(q))));results.replaceChildren();visible.slice(0,80).forEach(a=>{const b=document.createElement('button');b.type='button';b.className='county-result';b.dataset.areaName=a.name;b.setAttribute('aria-pressed',String(selected===a.name));const h=document.createElement('strong'),s=document.createElement('span');h.textContent=a.name;s.textContent=a.nation;b.append(h,s);b.addEventListener('click',()=>choose(a));results.append(b);});if(!visible.length){const p=document.createElement('p');p.className='fine-print';p.textContent='No matching place. Try a county name or a nearby town.';results.append(p);}}
function hover(el,name){el.addEventListener('pointermove',e=>{const b=$('.map-canvas').getBoundingClientRect();tooltip.textContent=name;tooltip.hidden=false;tooltip.style.left=Math.max(2,Math.min(e.clientX-b.left+12,b.width-170))+'px';tooltip.style.top=Math.max(2,e.clientY-b.top-36)+'px';});el.addEventListener('pointerleave',()=>tooltip.hidden=true);el.addEventListener('blur',()=>tooltip.hidden=true);}
function bindShape(el,rec){el.dataset.areaName=rec.name;el.dataset.nation=rec.nation;el.setAttribute('role','button');el.setAttribute('tabindex','-1');el.setAttribute('aria-label','Explore '+rec.name);el.setAttribute('aria-pressed','false');el.addEventListener('click',()=>choose(rec));el.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();choose(rec);}if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const all=[...svg.querySelectorAll('[role=button]')].filter(x=>x.style.display!=='none'&&x.closest('g')?.style.display!=='none'),i=all.indexOf(el),d=['ArrowRight','ArrowDown'].includes(e.key)?1:-1;const target=all[e.key==='Home'?0:e.key==='End'?all.length-1:(i+d+all.length)%all.length];all.forEach(x=>x.setAttribute('tabindex','-1'));target?.setAttribute('tabindex','0');target?.focus();}});hover(el,rec.name);}
function filter(){root.querySelectorAll('[data-map-nation]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mapNation===nation)));const nodes=[...svg.querySelectorAll('[data-nation]')];nodes.forEach(el=>el.style.display=(nation==='all'||el.dataset.nation===nation)?'':'none');const visible=nodes.filter(el=>el.style.display!=='none');visible.forEach((el,i)=>el.setAttribute('tabindex',i===0?'0':'-1'));if(nation==='all')setView([0,0,600,660]);else zoomFit(visible);list();}
root.querySelectorAll('[data-map-nation]').forEach(b=>b.addEventListener('click',()=>{nation=b.dataset.mapNation;filter();}));search.addEventListener('input',list);
root.querySelectorAll('[data-map-zoom]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.mapZoom;if(action==='reset'){filter();return;}const f=action==='in'?.72:1/.72;const w=Math.max(70,Math.min(1000,view[2]*f)),h=w*1.1;setView([view[0]+(view[2]-w)/2,view[1]+(view[3]-h)/2,w,h]);}));
// Pointer-drag only with a mouse: single-finger phone scrolling remains native.
let drag=null;svg.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button===0&&view[2]<590&&!e.target.closest('[role=button]')){drag={x:e.clientX,y:e.clientY,view:[...view]};svg.setPointerCapture(e.pointerId);}});svg.addEventListener('pointermove',e=>{if(drag){const r=svg.getBoundingClientRect();setView([drag.view[0]-(e.clientX-drag.x)*view[2]/r.width,drag.view[1]-(e.clientY-drag.y)*view[3]/r.height,view[2],view[3]]);}});svg.addEventListener('pointerup',()=>drag=null);svg.addEventListener('pointercancel',()=>drag=null);
async function json(url,timeout=8000){const ctrl=new AbortController(),id=setTimeout(()=>ctrl.abort(),timeout);try{const r=await fetch(url,{signal:ctrl.signal,credentials:'omit'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(id);}}
function decodeTopology(t){if(t.type!=='Topology'||!t.objects?.utla)throw Error('Unsupported ONS data');const arcs=t.arcs.map(a=>{let x=0,y=0;return a.map(p=>{if(t.transform){x+=p[0];y+=p[1];return[x*t.transform.scale[0]+t.transform.translate[0],y*t.transform.scale[1]+t.transform.translate[1]];}return p;});});const ring=ids=>ids.flatMap((id,i)=>{let pts=id<0?[...arcs[~id]].reverse():arcs[id];return i?pts.slice(1):pts;});return [...new Map(t.objects.utla.geometries.filter(g=>(!g.properties.start||g.properties.start<=2025)&&(!g.properties.end||g.properties.end>=2025)).map(g=>[g.properties.areacd,g])).values()].map(g=>({name:g.properties.areanm,code:g.properties.areacd,rings:(g.type==='Polygon'?[g.arcs]:g.arcs).flatMap(p=>p.map(ring))}));}
async function boundaries(){try{let t;try{t=await json('/data/uk-topo.json',2500);}catch{t=await json('https://raw.githubusercontent.com/ONSdigital/uk-topojson/aa84341201698f59b26998ca39d2b578df4b6d78/output/topo.json');}const decoded=decodeTopology(t);if(!decoded.length||Math.abs(decoded[0].rings[0][0][0])>180)throw Error('Coordinate system not supported');features=decoded;geo.replaceChildren();pins.replaceChildren();const all=new Map(areas.map(a=>[a.name,a]));features.forEach(f=>{const guide=guideFor(f.name,f.code),rec=makeRecord(f.name,nationFor(f.code),guide);all.set(rec.name,rec);const p=shape('path',{d:f.rings.map(line).join(''),class:'map-region','fill-rule':'evenodd'});bindShape(p,rec);geo.append(p);});records=[...all.values()].sort((a,b)=>a.name.localeCompare(b.name,'en-GB'));hasBoundaries=true;note.textContent='ONS upper-tier counties and council areas, 2025 geography. Simplified boundaries; not confirmed coverage. Contains OS and ONS data, Crown copyright and database right. Open Government Licence.';filter();}catch{note.textContent='Approximate area markers on a Natural Earth country outline. Detailed county boundaries are unavailable; all area links still work.';}}
async function start(){try{const [a,outline]=await Promise.all([json('/data/area-map.json'),json('/data/uk-outline.json')]);areas=a;records=a;geo.replaceChildren();outline.polygons.forEach(r=>geo.append(shape('path',{d:line(r),class:'map-base'})));areas.forEach(a=>{const [x,y]=project(a.centre),g=shape('g',{class:'map-pin',transform:`translate(${x.toFixed(2)} ${y.toFixed(2)})`});g.append(shape('circle',{r:9,class:'pin-hit'}),shape('circle',{r:4.3}));bindShape(g,a);pins.append(g);});filter();const io=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){io.disconnect();boundaries();}},{rootMargin:'200px'});io.observe(root);}catch{note.textContent='The map data is unavailable. Use the complete location directory below.';root.querySelectorAll('[data-area-name]').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.areaName;const q=new URLSearchParams({quote:'1',location:n});location.assign('/?'+q);}));}}
window.SunwardMap={decodeTopology,project,select:name=>{const r=records.find(a=>a.name===name);if(r)choose(r);},get status(){return {areas:records.length,boundaries:hasBoundaries,nation,selected};}};start();
})();
