/* Accessible, dependency-free enhancement layer. No tracking or persistent personal data. */
(() => {'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],params=new URLSearchParams(location.search),names={tesla:'Tesla Powerwall 3',sigenergy:'Sigenergy SigenStor',none:'Solar panels only'},links={tesla:'/battery-storage/tesla-powerwall/',sigenergy:'/battery-storage/sigenergy/',none:'/solar-pv/'};
const state=window.SunwardState=Object.assign({product:'tesla',capacity:13.5,area:(params.get('location')||'').slice(0,140)},window.SunwardState||{});
const init=params.get('product')||(location.pathname.includes('/sigenergy/')?'sigenergy':null)||$('.hero-stage')?.dataset.defaultProduct||'tesla';
function applyProduct(value,{syncBattery=true}={}){if(!Object.hasOwn(names,value))value='tesla';state.product=value;state.capacity=value==='sigenergy'?16:value==='tesla'?13.5:0;$$('[data-product]').forEach(b=>{b.classList.toggle('selected',b.dataset.product===value);b.setAttribute('aria-pressed',String(b.dataset.product===value));});$$('[data-installed-product]').forEach(g=>g.style.display=g.dataset.installedProduct===value?'':'none');$$('[data-product-label]').forEach(e=>e.textContent=value==='tesla'?'Tesla Powerwall 3 \u00b7 13.5 kWh':value==='sigenergy'?'SigenStor \u00b7 2-module illustration':'Solar PV \u00b7 no battery shown');$$('[data-product-detail]').forEach(a=>{a.href=links[value];a.firstChild.textContent=value==='none'?'Explore solar PV ':'Take a closer look ';});const bt=$('#battery-toggle');if(bt&&syncBattery){bt.checked=value!=='none';bt.dispatchEvent(new Event('input',{bubbles:true}));}const cp=$('[data-calculator-product]');if(cp)cp.textContent=value==='none'?'Solar-only illustration. Add storage to compare the effect.':`Storage illustration: ${state.capacity} kWh. Common assumptions, not a ${names[value]} performance forecast.`;$$('a[href*="quote=1"]').forEach(a=>{const u=new URL(a.href);if(!a.hasAttribute('data-fixed-product'))u.searchParams.set('product',value);a.href=u.pathname+u.search+u.hash;});updateQuoteNote();if($('.hero-visual.night')&&value==='none'&&$('#energy-message'))$('#energy-message').textContent='Sun down. The grid is still there.';}
function updateQuoteNote(){const e=$('[data-quote-selection]');if(e)e.textContent=(state.area?state.area+' \u00b7 ':'')+names[state.product]+' \u00b7 preference for discussion';}
$$('[data-product]').forEach(b=>b.addEventListener('click',()=>applyProduct(b.dataset.product)));
$$('[data-select-product]').forEach(b=>b.addEventListener('click',()=>{if(!$('.hero-stage')){location.assign('/?product='+b.dataset.selectProduct);return;}applyProduct(b.dataset.selectProduct);$('.hero-stage').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'center'});}));
const productDialog=$('#product-detail-dialog');if(productDialog){$('[data-close-product]').addEventListener('click',()=>productDialog.close());productDialog.addEventListener('close',()=>document.body.classList.toggle('modal-open',Boolean($('dialog[open]'))));productDialog.addEventListener('click',e=>{if(e.target!==productDialog)return;const r=productDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)productDialog.close();});$$('[data-product-detail]').forEach(a=>a.addEventListener('click',e=>{if(state.product==='none')return;e.preventDefault();$('#product-dialog-title').textContent=names[state.product];$('[data-detail-drawing]').innerHTML=window.SUNWARD_PRODUCT_RENDERS[state.product];$('[data-detail-link]').href=links[state.product];productDialog.showModal();document.body.classList.add('modal-open');}));}
$('#battery-toggle')?.addEventListener('change',e=>applyProduct(e.target.checked?(state.product==='none'?'tesla':state.product):'none',{syncBattery:false}));
// Preserve the base page's day/night behaviour. Inner service pages use this equivalent.
if(!window.Sunward)$$('[data-time]').forEach(b=>b.addEventListener('click',()=>{const night=b.dataset.time==='night';$('#hero-visual')?.classList.toggle('night',night);$$('[data-time]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});if($('#energy-mode'))$('#energy-mode').textContent=night?'AFTER THE SUN GOES DOWN':'DAYTIME, DONE BETTER';if($('#energy-message'))$('#energy-message').textContent=night?(state.product==='none'?'The grid is still there.':'A little sunshine, saved.'):'Hello sunshine. Hello energy.';}));
$$('[data-time]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.time==='night'&&state.product==='none'&&$('#energy-message'))$('#energy-message').textContent='Sun down. The grid is still there.';}));
const form=$('[data-postcode-start]');if(form)form.addEventListener('submit',e=>{e.preventDefault();const input=$('#start-postcode'),error=$('#start-postcode-error'),compact=input.value.toUpperCase().replace(/\s+/g,'');if(!/^(GIR0AA|[A-Z]{1,2}[0-9][A-Z0-9]?[0-9][A-Z]{2})$/.test(compact)){error.hidden=false;error.textContent='Enter a full UK postcode, for example GU1 1AA.';input.setAttribute('aria-invalid','true');input.focus();return;}input.removeAttribute('aria-invalid');error.hidden=true;const formatted=compact.slice(0,-3)+' '+compact.slice(-3);input.value=formatted;const trigger=$('[data-start-quote]');trigger.dataset.interest=state.product==='none'?'solar':'both';trigger.click();$('#postcode').value=formatted;updateQuoteNote();});
$('#quote-dialog')?.addEventListener('click',updateQuoteNote);
document.addEventListener('sunward:area',updateQuoteNote);
// Open in-place on the homepage; keep national-page links crawlable and usable without JS.
if(window.Sunward)document.addEventListener('click',e=>{
 const a=e.target.closest('a[href]');if(!a)return;const u=new URL(a.href);
 if(u.origin!==new URL(document.baseURI).origin||u.pathname!=='/'||u.searchParams.get('quote')!=='1')return;
 e.preventDefault();if(u.searchParams.get('location'))state.area=u.searchParams.get('location').slice(0,140);
 const trigger=$('[data-start-quote]');if(!trigger)return;
 trigger.dataset.interest=u.searchParams.get('interest')||(state.product==='none'?'solar':'both');
 trigger.click();updateQuoteNote();
});

const stories={morning:['07:00 / WAKE UP','The kettle\'s on.<br>The day is yours.','Stored energy can help with the morning routine before your panels are producing much. Your home still draws from the grid whenever it needs to.','Start the day with energy in reserve.'],midday:['12:00 / MAKE IT','A roof that does<br>more than shelter.','Use solar electricity as it is generated. Depending on conditions and demand, surplus can charge your battery or be exported under a suitable arrangement.','Daylight to your home. Surplus to storage or the grid.'],evening:['19:00 / KEEP GOING','The sun clocks off.<br>Your evening doesn\'t.','A charged battery can cover some evening demand. Available energy, inverter power and your settings determine how much; the grid supplies the rest.','Stored energy helps carry the evening.'],night:['02:00 / THINK AHEAD','A quieter house.<br>A smarter schedule.','A suitable battery and time-of-use tariff may allow cheaper grid charging overnight. Check tariff windows, losses and the next day\'s needs before scheduling.','Illustrative off-peak charging, subject to your tariff.']};
function story(key){const s=stories[key];if(!s)return;$$('[data-story]').forEach(b=>{const on=b.dataset.story===key;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;});$('#story-panel').setAttribute('aria-labelledby','story-tab-'+key);$('[data-story-kicker]').textContent=s[0];$('[data-story-title]').innerHTML=s[1];$('[data-story-text]').textContent=s[2];$('[data-flow-caption]').textContent=s[3];$('[data-flow="solar-home"]').classList.toggle('inactive',['evening','night'].includes(key));$('[data-flow="battery-home"]').classList.toggle('reverse',['morning','evening'].includes(key));}
$$('[data-story]').forEach((b,i)=>{b.addEventListener('click',()=>story(b.dataset.story));b.addEventListener('keydown',e=>{const tabs=$$('[data-story]');if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[n].focus();story(tabs[n].dataset.story);}});});
const lab=$('[data-tariff-lab]');if(lab){const num=(name)=>{const el=lab.querySelector('[name="'+name+'"]');const n=Number(el.value);return Math.min(+el.max,Math.max(+el.min,Number.isFinite(n)?n:0));};function calculate(){const imp=lab.dataset.tariffLab==='import';const value=imp?num('shift')*(num('peak')-num('cheap')/(num('efficiency')/100))*num('days')/100-num('standing')*365/100:num('exported')*num('rate')/100;$('[data-lab-result]').textContent=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(value);if(imp)$('[data-lab-explain]').textContent=value<0?'These inputs indicate an additional annual cost, not a saving. Equipment and all other costs remain excluded.':'After the stated charging losses and standing-charge difference. Before equipment and all other costs.';return value;}lab.querySelectorAll('input').forEach(i=>{i.addEventListener('input',calculate);i.addEventListener('blur',()=>{i.value=num(i.name);calculate();});});window.SunwardTariff={calculate};calculate();}
// Keep the navigation predictable for pointer, keyboard and touch users.
$$('.nav-dropdown').forEach(d=>{document.addEventListener('click',e=>{if(!d.contains(e.target))d.open=false;});d.addEventListener('keydown',e=>{if(e.key==='Escape'){d.open=false;d.querySelector('summary').focus();}});});
let tick=false;const progress=$('.site-progress');function updateProgress(){if(progress){const total=document.documentElement.scrollHeight-innerHeight;progress.style.width=(total>0?Math.min(100,scrollY/total*100):0)+'%';}tick=false;}addEventListener('scroll',()=>{if(!tick){tick=true;requestAnimationFrame(updateProgress);}},{passive:true});updateProgress();
if($('#story-panel'))story('morning');
applyProduct(init);
window.SunwardUI={selectProduct:applyProduct,state};
})();
